Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2022-12, with the labels that each got.

#56 API 수정사항 반영
  pages/detail/index.tsx
  pages/mine/management/index.tsx
  src/api/meeting/index.ts
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupList/Card/ManagementButton.tsx
  src/components/page/groupList/Grid/List.tsx
  src/components/page/groupManagement/GroupInformation.tsx
  src/components/page/groupManagement/ListItem.tsx
Labels: size/M

#54 SyncLoader 추가
  package.json
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/mine/management/index.tsx
  src/api/meeting/index.ts
  src/components/loader/Loader.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupList/Card/ManagementButton.tsx
  src/components/page/groupList/Grid/List.tsx
  src/components/page/groupManagement/GroupInformation.tsx
  src/components/page/groupManagement/ListItem.tsx
  yarn.lock
Labels: size/L

#52 Card 컴포넌트 Image 비율 및 fit 조정
  src/components/page/groupList/Card/ManagementButton.tsx
  src/components/page/groupList/Card/index.tsx
  src/components/page/groupList/Grid/Layout.tsx
  src/components/page/groupList/Pagination.tsx
  src/constants/font.ts
Labels: size/M

#37 chore: 배포 Action 추가
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  package.json
  yarn.lock
Labels: size/XL

#61 프로덕션 배포 액션 이름 수정
  .github/workflows/deploy-production.yml
Labels: size/XS

#63 프로덕션 배포를 위한 main 업데이트
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  package.json
  yarn.lock
Labels: size/XXL

#60 feat: MultiSelect 공통 컴포넌트로 분리
  src/components/filter/MultiSelect/SelectComboBoxItem.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/page/groupList/Filter/Select/index.tsx
  src/components/page/groupList/Filter/index.tsx
  src/providers/groupList/SelectListVisionProvider.tsx
Labels: size/L

#59 신청자 관리 페이지 수정사항 반영
  pages/mine/management/index.tsx
  public/assets/svg/arrow_medium_right_gray.svg
  public/assets/svg/arrow_small_right_purple.svg
  public/assets/svg/invitation.svg
  src/components/page/groupManagement/GroupInformation.tsx
  src/components/page/groupManagement/GroupInformationSkeleton.tsx
  src/components/page/groupManagement/ItemDescriptionBox.tsx
  src/components/page/groupManagement/ListItem.tsx
  src/components/page/groupManagement/ListSkeleton.tsx
  src/constants/font.ts
  src/data/options.ts
  stitches.config.ts
Labels: size/XL

#68 모임 관리 페이지 반응형 작업
  pages/mine/management/index.tsx
  public/assets/svg/.gitkeep
  public/assets/svg/arrow_mini.svg
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupDetail/RecruitmentStatusList.tsx
  src/components/page/groupList/Pagination.tsx
  src/components/page/groupManagement/GroupInformation.tsx
  src/components/page/groupManagement/GroupInformationSkeleton.tsx
  src/components/page/groupManagement/ItemDescriptionBox.tsx
  src/components/page/groupManagement/ListItem.tsx
  src/components/page/groupManagement/ListSkeleton.tsx
  src/constants/font.ts
  stitches.config.ts
Labels: size/XL

#67 모임 상세 페이지 반응형 작업
  pages/_app.tsx
  pages/detail/index.tsx
  pages/mine/management/index.tsx
  public/assets/svg/.gitkeep
  public/assets/svg/arrow_mini.svg
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/page/groupDetail/Carousel.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupDetail/RecruitmentStatusList.tsx
  src/components/page/groupList/Pagination.tsx
  src/components/page/groupManagement/GroupInformation.tsx
  src/components/page/groupManagement/GroupInformationSkeleton.tsx
  src/components/page/groupManagement/ItemDescriptionBox.tsx
  src/components/page/groupManagement/ListItem.tsx
  src/components/page/groupManagement/ListSkeleton.tsx
  src/components/tabList/TabList.tsx
  src/constants/font.ts
  stitches.config.ts
Labels: size/XL

#77 모임 생성 후 생성된 모임 상세 페이지로 이동
  pages/make/index.tsx
  src/api/group.ts
Labels: size/S

#78 Header 루팡질
  next.config.js
  pages/_app.tsx
  public/assets/icon/.gitkeep
  public/assets/icon/icon-back.svg
  public/assets/icon/icon-logo-mobile.svg
  public/assets/icon/icon-logo.svg
  public/assets/icon/icon-member.svg
  public/assets/icon/icon-menu.svg
  public/assets/icon/icon-profile.svg
  shim-svg.d.ts
  src/api/index.ts
  src/api/members/hooks.ts
  src/api/members/index.ts
  src/api/members/type.ts
  src/components/header/Header.tsx
  src/constants/link.ts
  src/hooks/usePlaygroundLink.ts
  stitches.config.ts
  styles/globals.css
Labels: size/XL

#74 모임 생성/수정 페이지 반응형 디자인 적용
  pages/edit/index.tsx
  pages/make/index.tsx
  public/assets/svg/check.svg
  public/assets/svg/x.svg
  src/api/group.ts
  src/components/Form/FileInput/index.tsx
  src/components/Form/Presentation/ImagePreview/index.tsx
  src/components/Form/Presentation/index.tsx
  src/components/Form/TableOfContents/index.tsx
  src/components/Form/TextInput/index.tsx
  src/components/Form/Textarea/index.tsx
Labels: size/L

#79 Feat/#65
  src/api/index.ts
  src/components/header/Header.tsx
Labels: size/M

#81 모임 상세 페이지 캐러셀 반응형 작업
  src/components/page/groupDetail/Carousel.tsx
  src/components/page/groupDetail/NextArrow.tsx
  stitches.config.ts
Labels: size/M

#72 인증 연동
  pages/_app.tsx
  src/api/group.ts
  src/api/index.ts
  src/api/meeting/index.ts
  src/api/user/index.ts
  src/hooks/useAuth.ts
Labels: size/L

#82 [모임 리스트] 반응형 및 스켈레톤 작업
  package.json
  pages/index.tsx
  pages/mine/index.tsx
  public/assets/svg/arrow_mobile_right.svg
  public/assets/svg/write.svg
  src/components/filter/MultiSelect/BottomSheet.tsx
  src/components/filter/MultiSelect/SelectComboBoxItem.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/header/Header.tsx
  src/components/page/groupList/Card/ManagementButton.tsx
  src/components/page/groupList/Card/Skeleton.tsx
  src/components/page/groupList/Card/Status.tsx
  src/components/page/groupList/Card/index.tsx
  src/components/page/groupList/Filter/Result/InitializationButton.tsx
  src/components/page/groupList/Filter/Result/ResultItem.tsx
  src/components/page/groupList/Filter/Result/index.tsx
  src/components/page/groupList/Filter/Search/Mobile.tsx
  src/components/page/groupList/Filter/Search/index.tsx
  src/components/page/groupList/Grid/Layout.tsx
  src/components/page/groupList/Grid/List.tsx
  src/components/tabList/TabList.tsx
  src/components/util/layout/Flex.tsx
  src/constants/font.ts
Labels: size/XL

#85 인증 토큰 scheme 빠진 것 수정
  src/hooks/useAuth.ts
Labels: size/XS

#88 헤더 user name 수정 및 logout 연동
  src/components/header/Header.tsx
Labels: size/XS

#87 프로덕션 배포
  src/components/header/Header.tsx
  src/hooks/useAuth.ts
Labels: size/S

#92 모임개설을 막고 있는 헤더의 무언가 고치기
  src/components/header/Header.tsx
Labels: size/XS

#93 모임 관리 페이지 리스트 아이템
  pages/mine/management/index.tsx
  src/components/page/groupManagement/InvitationListItem.tsx
  src/components/page/groupManagement/InvitationModal.tsx
  src/components/page/groupManagement/ItemDescriptionBox.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/components/page/groupManagement/ManagementListSkeleton.tsx
  stitches.config.ts
Labels: size/L

#94 Crew API 서버에서 제공하는 로그인 API 연동
  pages/_app.tsx
  src/api/auth/index.ts
  src/api/index.ts
  src/hooks/useAuth.ts
Labels: size/M

#95 모임 상세 페이지 초대 기능 반영
  pages/_app.tsx
  pages/detail/index.tsx
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupDetail/NextArrow.tsx
  src/constants/status.ts
Labels: size/L

#96 프로덕션 배포
  pages/_app.tsx
  pages/detail/index.tsx
  pages/mine/management/index.tsx
  src/api/auth/index.ts
  src/api/index.ts
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/header/Header.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupDetail/NextArrow.tsx
  src/components/page/groupManagement/InvitationListItem.tsx
  src/components/page/groupManagement/InvitationModal.tsx
  src/components/page/groupManagement/ItemDescriptionBox.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/components/page/groupManagement/ManagementListSkeleton.tsx
  src/constants/status.ts
  src/hooks/useAuth.ts
  stitches.config.ts
Labels: size/XL
