Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-01, with the labels that each got.

#98 Crew API 인증 토큰에 빠진 auth scheme 추가
  src/hooks/useAuth.ts
Labels: size/XS

#99 프로덕션 배포
  src/hooks/useAuth.ts
Labels: size/XS

#103 Playground API token 설정 타이밍 수정
  src/hooks/useAuth.ts
Labels: size/XS

#104 프로덕션 배포
  src/hooks/useAuth.ts
Labels: size/XS

#106 토큰 state가 싱크 안 맞는 이슈 수정
  src/hooks/useAuth.ts
Labels: size/XS

#107 프로덕션 배포
  src/hooks/useAuth.ts
Labels: size/XS

#109 모임 참여자 링크 수정
  src/api/user/index.ts
  src/components/header/Header.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupDetail/RecruitmentStatusList.tsx
  src/components/page/groupManagement/InvitationListItem.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
Labels: size/M

#111 모임 생성 후 잘못된 경로로 이동하는 버그 수정
  pages/make/index.tsx
  src/api/group.ts
Labels: size/S

#112 모임 수정 안되는 버그 수정
  pages/edit/index.tsx
  src/api/group.ts
Labels: size/S

#110 모임 관리 페이지 필터 변경 및 초대 취소 api 적용
  pages/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/filter/MultiSelect/index.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupList/Card/Status.tsx
  src/components/page/groupList/Card/index.tsx
  src/components/page/groupList/Filter/index.tsx
  src/components/page/groupManagement/Filter/index.tsx
  src/components/page/groupManagement/GroupInformation.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/components/page/groupManagement/ManagementListSkeleton.tsx
  src/constants/option.ts
  src/constants/status.ts
  src/data/options.ts
  src/hooks/queryString/custom.ts
  stitches.config.ts
Labels: size/XL

#114 모임 초대 모달 추가
  pages/mine/management/index.tsx
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/Form/Select/index.tsx
  src/components/Form/TextInput/index.tsx
  src/components/modal/DefaultModal.tsx
  src/components/page/groupManagement/InvitationListItem.tsx
  src/components/page/groupManagement/InvitationModal.tsx
  src/components/page/groupManagement/InvitationModal/InvitationModal.tsx
  src/components/page/groupManagement/InvitationModal/SelectUsersStep.tsx
  src/data/options.ts
  src/hooks/useDebounce.ts
Labels: size/XL

#115 프로덕션 배포
  pages/edit/index.tsx
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  src/api/group.ts
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/api/user/index.ts
  src/components/Form/Select/index.tsx
  src/components/Form/TextInput/index.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/header/Header.tsx
  src/components/modal/DefaultModal.tsx
  src/components/page/groupDetail/Carousel.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupDetail/RecruitmentStatusList.tsx
  src/components/page/groupList/Card/Status.tsx
  src/components/page/groupList/Card/index.tsx
  src/components/page/groupList/Filter/index.tsx
  src/components/page/groupManagement/Filter/index.tsx
  src/components/page/groupManagement/GroupInformation.tsx
  src/components/page/groupManagement/InvitationListItem.tsx
  src/components/page/groupManagement/InvitationModal.tsx
  src/components/page/groupManagement/InvitationModal/InvitationModal.tsx
  src/components/page/groupManagement/InvitationModal/SelectUsersStep.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/components/page/groupManagement/ManagementListSkeleton.tsx
  src/constants/option.ts
  src/constants/status.ts
  src/data/options.ts
  src/hooks/queryString/custom.ts
  src/hooks/useDebounce.ts
  stitches.config.ts
  styles/globals.css
Labels: size/XXL

#116 프로덕션 배포
  pages/detail/index.tsx
  pages/mine/management/index.tsx
  src/components/page/groupManagement/InvitationListItem.tsx
Labels: size/S

#117 스타일링 일부 수정해서 프로덕션 배포
  src/components/Form/TableOfContents/index.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupDetail/RecruitmentStatusList.tsx
  src/components/page/groupList/Card/Skeleton.tsx
  src/components/page/groupList/Filter/Search/Mobile.tsx
  src/components/page/groupList/Grid/Layout.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  stitches.config.ts
Labels: size/M

#119 필터 및 검색 결과에 대한 반응형 미흡한 부분 수정
  src/components/page/groupList/EmptyView.tsx
  src/components/page/groupList/Filter/Result/InitializationButton.tsx
  src/components/page/groupList/Filter/Result/ResultItem.tsx
  src/components/page/groupList/Filter/Result/index.tsx
  src/components/page/groupList/Filter/index.tsx
Labels: size/M

#120 프로덕션 배포
  pages/_document.tsx
  pages/edit/index.tsx
  pages/make/index.tsx
  pages/mine/management/index.tsx
  src/api/group.ts
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/form/ErrorMessage/index.tsx
  src/components/form/FileInput/index.tsx
  src/components/form/FormController/index.tsx
  src/components/form/HelpMessage/index.tsx
  src/components/form/Label/index.tsx
  src/components/form/Presentation/ImagePreview/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/Button/index.tsx
  src/components/form/Select/OptionItem/index.tsx
  src/components/form/Select/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/form/TextInput/index.tsx
  src/components/form/Textarea/index.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupList/Card/Status.tsx
  src/components/page/groupList/EmptyView.tsx
  src/components/page/groupList/Filter/Result/InitializationButton.tsx
  src/components/page/groupList/Filter/Result/ResultItem.tsx
  src/components/page/groupList/Filter/Result/index.tsx
  src/components/page/groupList/Filter/index.tsx
  src/components/page/groupManagement/InvitationModal/InvitationModal.tsx
  src/components/page/groupManagement/InvitationModal/SelectUsersStep.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/constants/option.ts
Labels: size/L
