Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-12, with the labels that each got.

#594 풀구 헤더 버전업
  package.json
  yarn.lock
Labels: size/S

#595 프로덕션 배포
  .github/CODEOWNERS
  package.json
  pages/post/index.tsx
  src/components/feed/FeedActionButton/FeedActionButton.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/hooks/useToast/Toast.tsx
  yarn.lock
Labels: size/L

#601 breakpoint 수정
  pages/_app.tsx
  src/components/page/meetingDetail/Feed/Skeleton/FeedItemSkeleton.tsx
  stitches.config.ts
Labels: size/S

#587 Feed 컴포넌트 인터페이스 수정: 모임 정보 추가
  pages/index.tsx
  src/components/button/Arrow.tsx
  src/components/page/meetingDetail/Feed/FeedItem/MeetingInfo.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/M

#603 12/08 배포 건에 대한 앰플리튜드 신규 이벤트 대응
  pages/list/index.tsx
  src/ampli/index.ts
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/L

#608 모임 피드 (홈화면) 플로팅 버튼 UI 구현
  pages/index.tsx
  public/assets/svg/floating_button_feed_icon.svg
  public/assets/svg/floating_button_group_icon.svg
  src/components/modal/FloatingButtonModal.tsx
  src/components/modal/ModalBackground.tsx
  src/components/page/postList/FloatingButton/index.tsx
Labels: size/L

#610 selectMeeting 컴포넌트 모바일 대응
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/feed/Modal/SelectMeeting/index.tsx
  src/components/page/meetingDetail/Feed/FeedItem/MeetingInfo.tsx
  src/components/page/postList/FloatingButton/index.tsx
Labels: size/L

#614 내가 속한 모임 없음 모달 UI 작성
  src/components/modal/FloatingButtonModal.tsx
  src/components/modal/NoJoinedGroupModal.tsx
Labels: size/L

#616 피드 아이템 컴포넌트 확장(좋아요 버튼 합성, onClick props 추가)
  src/api/post/hooks.ts
  src/components/button/LikeButton.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/L

#602 피드 상세 뷰에 해당 모임 피드 리스트 추가
  pages/post/index.tsx
  public/assets/svg/arrow_card.svg
  public/assets/svg/comment_hover.svg
  public/assets/svg/like_hover.svg
  public/assets/svg/send.svg
  public/assets/svg/send_fill.svg
  public/assets/svg/share.svg
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
  src/components/feed/FeedCommentLikeSection/FeedCommentLikeSection.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
Labels: size/L

#613 플로팅 버튼 action 연결 및 api 연결
  pages/index.tsx
  src/__generated__/schema.d.ts
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/api/user/index.ts
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/modal/NoJoinedGroupModal.tsx
  src/components/page/meetingDetail/Feed/FeedItem/MeetingInfo.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/postList/FloatingButton/index.tsx
Labels: size/L

#618 이슈 해결
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
  src/components/util/auth.ts
Labels: size/S

#620 개발 환경에서 인증 토큰을 환경 변수로 관리하도록 수정
  src/components/util/auth.ts
Labels: size/XS

#625 피드 상세페이지 스타일 이슈 수정
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/XS

#622 mockData 를 안뺏지뭐에요???
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
Labels: size/M

#623 피드 게시글 상세페이지에 전체 피드 게시글 목록 UI 추가
  pages/post/index.tsx
  src/api/post/hooks.ts
Labels: size/M

#628 내모임 클릭이 이상하요
  pages/mine/index.tsx
Labels: size/XS

#631 피드 게시글 상세페이지 스타일 이슈 수정
  pages/post/index.tsx
Labels: size/M

#632 피드 좋아요 합성
  pages/index.tsx
  src/components/page/meetingDetail/Feed/FeedItem/MeetingInfo.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/M

#635 피드 게시글 상세페이지에서는 스크롤 복원 안되도록 처리
  src/hooks/useScrollRestoration.ts
Labels: size/XS

#634 피드 상세 수정
  pages/post/index.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/M

#638 피드작성이 안떠요
  src/api/user/index.ts
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/postList/FloatingButton/index.tsx
Labels: size/S

#640 스크롤 위치 blacklist 추가
  src/hooks/useScrollRestoration.ts
Labels: size/XS

#642 피드개설 디자인 이슈 해결
  src/components/feed/Modal/SelectMeeting/SelectMeetingOptionItem.tsx
  src/components/feed/Modal/SelectMeeting/index.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/postList/FloatingButton/index.tsx
Labels: size/S

#644 margin-left 맞추기
  src/components/feed/Modal/FeedFormPresentation.tsx
Labels: size/XS

#647 같은놈을 여러번 찌르네요?
  pages/index.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/XS

#648 프로덕션 배포
  pages/index.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/XS

#650 페이지 빠바박
  package.json
  pages/index.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  yarn.lock
Labels: size/M

#652 아이폰 스타일 이슈 대응
  src/components/modal/FloatingButtonModal.tsx
Labels: size/XS

#655 oberverTarget의 height는 없어도 되자나요?
  pages/index.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/S

#653 프로덕션 배포
  package.json
  pages/index.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  yarn.lock
Labels: size/M

#657 앰플리튜드 로깅 추가
  pages/index.tsx
Labels: size/S

#660 피드 상세 리스트 뷰 내 카드 width를 핸드오프와 동일하게 수정
  pages/post/index.tsx
Labels: size/XS

#658 프로덕션 배포
  pages/index.tsx
  pages/post/index.tsx
Labels: size/S
