Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-10, with the labels that each got.

#484 댓글 작성 시간이 몇초 후 라고 표기되는 버그 수정 및 워딩 변경
  src/utils/dayjs.ts
Labels: size/S

#486 피드 게시글 삭제 기능 추가
  pages/post/index.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/M

#490 아바타 컴포넌트 스타일 수정
  src/components/avatar/AvatarGroup.tsx
Labels: size/XS

#499 피드 상세 뷰 이미지 영역 패딩 수정
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/XS

#502 게시글 상세 뷰 모바일 스타일 적용
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/S

#503 피드 상세 뷰 가운데 중앙 정렬
  pages/post/index.tsx
Labels: size/XS

#505 피드 상세 뷰 댓글 입력 UI가 자리차지하는 스타일 이슈 수정
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
Labels: size/XS

#500 [이슈 02] 단락을 나누어 글을 작성했는데 붙어버리는 이슈 발생
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/page/meetingDetail/Feed/FeedItem.tsx
Labels: size/XS

#501 [이슈 04] 피드 리스트 뷰 MO와 PC 작성하기 CTA 버튼 색상 상이(주황색으로 통일)
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/XS

#506 [이슈 11] 모집 마감 태그 컬러 상이
  src/components/page/meetingDetail/DetailHeader.tsx
Labels: size/XS

#504 [제안 01] 피드 게시글 내 링크 하이퍼링크 기능 추가
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/XS

#510 피드 상세 뷰 수정 기능 연동
  pages/post/index.tsx
Labels: size/S

#508 피드 리스트에 좋아요 기능 추가
  pages/detail/index.tsx
  src/api/post/hooks.ts
  src/components/avatar/AvatarGroup.tsx
  src/components/page/meetingDetail/Feed/FeedItem.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/M

#512 comment input color change
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
Labels: size/XS

#514 [이슈 22] 피드 작성, 수정 모바일 뷰 타이틀 밑에 스트로크 제거
  src/components/feed/Modal/FeedFormPresentation.tsx
Labels: size/XS

#488 [이슈 14] 댓글 글쓴이 판별하는 변수, isMine 수정
  pages/post/index.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
Labels: size/S

#519 group category border color change
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
Labels: size/XS

#516 하단에 여백 없는 것 수정
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/XS

#524 [이슈 20] 모바일 뷰 댓글 width 넘어갈 시 줄바꿈 안 되는 현상 해결
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
Labels: size/XS

#525 댓글 작성한 사람이 게시글 작성한 사람인지 확인하는 로직 수정
  pages/post/index.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
Labels: size/S

#522 피드 댓글 입력 UI 자동 리사이즈 기능 추가
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
Labels: size/S

#521 [이슈 15] mo뷰 카드 간 스페이싱에 그레이가 밝게 들어가는데 없음
  src/components/page/meetingDetail/Feed/FeedItem.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/S

#527 시간 표기해주는 형식 수정
  src/utils/dayjs.ts
Labels: size/XS

#529 피드 작성,수정뷰 x 아이콘에 cursor:pointer 추가
  src/components/feed/Modal/FeedFormPresentation.tsx
Labels: size/XS

#532 앰플리튜드 이벤트 로깅 셋업
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  ampli.json
  package.json
  pages/_app.tsx
  pages/post/index.tsx
  src/ampli/index.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  yarn.lock
Labels: size/XXL

#531 피드 상세 뷰 앰플리튜드 이벤트 로깅
  pages/post/index.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/M

#533 피드 리스트 앰플리튜드 로깅
  src/components/page/meetingDetail/Feed/FeedItem.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/M

#535 피드 작성 뷰 앰플리튜드 이벤트 로깅
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/utils/dayjs.ts
Labels: size/S

#538 [이슈 25] 피드 리스트에서 좋아요 클릭 시 다른 곳에서 산발적으로 아바타 컴포넌트가 바뀌는 이슈
  src/components/avatar/Avatar.tsx
  src/components/page/meetingDetail/Feed/FeedItem.tsx
Labels: size/S

#540 앰플리튜드 이벤트 로깅 수정
  pages/post/index.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
Labels: size/M

#541 모집마감은 피드 탭부터 뜨도록 수정
  pages/detail/index.tsx
Labels: size/S

#542 프로덕션 배포
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  .storybook/main.ts
  .storybook/preview.tsx
  ampli.json
  package.json
  pages/_app.tsx
  pages/detail/index.tsx
  pages/post/index.tsx
  public/assets/svg/comment.svg
  public/assets/svg/like_fill_in_comment.svg
  public/assets/svg/like_in_comment.svg
  src/__generated__/schema.d.ts
  src/ampli/index.ts
  src/api/index.ts
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/avatar/Avatar.tsx
  src/components/avatar/AvatarGroup.tsx
  src/components/feed/FeedActionButton/FeedActionButton.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentEditor/FeedCommentEditor.tsx
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
  src/components/feed/FeedCommentLikeSection/FeedCommentLikeSection.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.stories.ts
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.stories.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/feed/Modal/ImagePreview/index.tsx
  src/components/feed/Modal/feedSchema.ts
  src/components/modal/ModalBackground.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/Feed/EmptyView.tsx
  src/components/page/meetingDetail/Feed/FeedItem.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedCreateModal.tsx
  src/components/page/meetingDetail/NextArrow.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/util/auth.ts
  src/constants/feed.ts
  src/constants/index.ts
  src/constants/url.ts
  src/hooks/useComment/useComment.ts
  src/hooks/useComment/useCommentMutation.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useOverlay/Index.tsx
  src/hooks/useOverlay/OverlayController.tsx
  src/hooks/useOverlay/OverlayProvider.tsx
  src/stores/tokenStore.ts
  src/utils/dayjs.ts
  src/utils/truncateText.ts
  stitches.config.ts
  tsconfig.json
  yarn.lock
Labels: size/XXL

#544 피드 아이템 스타일 이슈
  src/components/page/meetingDetail/Feed/FeedItem.tsx
Labels: size/XS

#545 프로덕션 배포
  src/components/page/meetingDetail/Feed/FeedItem.tsx
Labels: size/XS

#547 주소창에 가려지는 스타일 이슈
  src/components/modal/ImageCarouselModal.tsx
Labels: size/XS

#549 신청자 관리 화면 스타일 이슈 수정
  src/components/page/meetingManagement/ManagementListItem.tsx
Labels: size/S

#554 피드 아이템 프로필 링크 이슈
  src/components/page/meetingDetail/Feed/FeedItem.tsx
Labels: size/XS

#555 프로덕션 배포
  src/components/page/meetingDetail/Feed/FeedItem.tsx
Labels: size/XS

#557 링크가 영역 벗어나는 이슈 해결
  src/components/page/meetingDetail/Information/InformationPanel.tsx
  src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx
Labels: size/S

#560 링크가 화면을 벗어나지 않도록 word-break 속성 지정
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/XS

#565 모임 상세 이미지 크기 이슈
  src/components/modal/ImageCarouselModal.tsx
Labels: size/XS

#562 앰플리튜드 로깅 작업
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  src/ampli/index.ts
  src/components/disclosure/Disclosure.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/page/meetingDetail/Carousel/NextArrow.tsx
  src/components/page/meetingDetail/Carousel/index.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/ApplicationModalContent.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Filter/Modal/Chip/ChipItem.tsx
  src/components/page/meetingList/Filter/Modal/Chip/index.tsx
  src/components/page/meetingList/Filter/Modal/OpenButton.tsx
  src/components/page/meetingList/Filter/Modal/Toggle/index.tsx
  src/components/page/meetingList/Pagination.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
Labels: size/XXL

#570 프로덕션 배포
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  src/ampli/index.ts
  src/components/disclosure/Disclosure.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/page/meetingDetail/Carousel/NextArrow.tsx
  src/components/page/meetingDetail/Carousel/index.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/ApplicationModalContent.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Filter/Modal/Chip/ChipItem.tsx
  src/components/page/meetingList/Filter/Modal/Chip/index.tsx
  src/components/page/meetingList/Filter/Modal/OpenButton.tsx
  src/components/page/meetingList/Filter/Modal/Toggle/index.tsx
  src/components/page/meetingList/Pagination.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
Labels: size/XXL

#563 피드 상세뷰 가로 스크롤 수정
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/XS
