Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-02, with the labels that each got.

#124 모집 인원 숫자 입력한 뒤 지울 때 0이 남는 이슈 해결
  src/components/form/Presentation/index.tsx
Labels: size/XS

#122 모임 생성하기 페이지 TableOfContents 수정
  pages/make/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  styles/globals.css
Labels: size/M

#126 모임 생성하기 버튼 더블클릭 시 모임 2개 생기는 이슈 해결
  pages/make/index.tsx
  src/components/form/Presentation/index.tsx
Labels: size/S

#127 프로덕션 배포
  pages/make/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/page/groupManagement/InvitationListItem.tsx
  src/components/page/groupManagement/InvitationModal/SelectUsersStep.tsx
  stitches.config.ts
  styles/globals.css
Labels: size/L

#132 모임 신청 시간 추가
  pages/_document.tsx
  pages/mine/management/index.tsx
  public/assets/img/img_example_1.jpg
  src/components/button/Arrow.tsx
  src/components/filter/MultiSelect/BottomSheet.tsx
  src/components/filter/MultiSelect/SelectComboBoxItem.tsx
  src/components/page/groupList/Filter/Search/index.tsx
  src/components/page/groupList/Grid/List.tsx
  src/components/page/groupList/Pagination.tsx
  src/components/page/groupManagement/InvitationModal/InvitationModal.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/components/tabList/TabList.tsx
  src/components/text/Text.tsx
  src/components/util/ErrorBoundary.tsx
  src/components/util/layout/Flex.tsx
  src/constants/font.ts
  src/hooks/queryString/index.ts
  src/providers/PortalProvider.tsx
  src/utils/bindThePages.ts
  src/utils/date.ts
  src/utils/styles.ts
  src/utils/urlToFile.ts
Labels: size/L

#130 카드의 모집기간에 모임기간이 보이는 오류 해결
  src/components/page/groupList/Card/index.tsx
Labels: size/XS

#133 프로덕션 배포
  .prettierrc
  pages/_app.tsx
  pages/_document.tsx
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  public/assets/img/img_example_1.jpg
  public/favicon.ico
  public/vercel.svg
  src/api/group.ts
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/button/Arrow.tsx
  src/components/filter/MultiSelect/BottomSheet.tsx
  src/components/filter/MultiSelect/SelectComboBoxItem.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/form/FileInput/index.tsx
  src/components/form/FormController/index.tsx
  src/components/form/Presentation/ImagePreview/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/OptionItem/index.tsx
  src/components/form/Select/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/form/TextInput/index.tsx
  src/components/header/Header.tsx
  src/components/modal/DefaultModal.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupDetail/RecruitmentStatusList.tsx
  src/components/page/groupList/Card/index.tsx
  src/components/page/groupList/Filter/Result/ResultItem.tsx
  src/components/page/groupList/Filter/Result/index.tsx
  src/components/page/groupList/Filter/Search/Mobile.tsx
  src/components/page/groupList/Filter/Search/index.tsx
  src/components/page/groupList/Grid/List.tsx
  src/components/page/groupList/Pagination.tsx
  src/components/page/groupManagement/GroupInformation.tsx
  src/components/page/groupManagement/InvitationListItem.tsx
  src/components/page/groupManagement/InvitationModal/InvitationModal.tsx
  src/components/page/groupManagement/InvitationModal/SelectUsersStep.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/components/tabList/TabList.tsx
  src/components/text/Text.tsx
  src/components/util/ErrorBoundary.tsx
  src/components/util/layout/Flex.tsx
  src/constants/font.ts
  src/hooks/queryString/index.ts
  src/hooks/useSessionStorage.ts
  src/providers/PortalProvider.tsx
  src/types/form.ts
  src/utils/bindThePages.ts
  src/utils/date.ts
  src/utils/styles.ts
  src/utils/urlToFile.ts
Labels: size/XXL

#134 conflict를 해결하면서 간격 하나가 사라졌어요!
  src/components/page/groupList/Card/index.tsx
Labels: size/XS

#135 프로덕션 배포
  src/components/page/groupList/Card/index.tsx
Labels: size/XS

#141 플그팀 헤더 적용
  package.json
  public/assets/icon/icon-back.svg
  public/assets/icon/icon-logo-mobile.svg
  public/assets/icon/icon-logo.svg
  public/assets/icon/icon-member.svg
  public/assets/icon/icon-menu.svg
  public/assets/icon/icon-profile.svg
  src/components/header/Header.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/modal/ModalBackground.tsx
  src/components/page/groupList/Card/index.tsx
  stitches.config.ts
  yarn.lock
Labels: size/XXL

#143 모임 참여자 시간 정보 추가
  pages/detail/index.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupList/Card/index.tsx
  src/components/page/groupManagement/ItemDescriptionBox.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/utils/date.ts
Labels: size/M

#147 멘토 구해요 툴팁 추가
  public/assets/svg/question_mark.svg
  src/components/page/groupDetail/DetailHeader.tsx
Labels: size/M

#146 폰트 적용 방법 수정
  public/assets/fonts/SUIT-Bold.otf
  public/assets/fonts/SUIT-Bold.woff2
  public/assets/fonts/SUIT-ExtraBold.otf
  public/assets/fonts/SUIT-ExtraBold.woff2
  public/assets/fonts/SUIT-ExtraLight.otf
  public/assets/fonts/SUIT-ExtraLight.woff2
  public/assets/fonts/SUIT-Heavy.otf
  public/assets/fonts/SUIT-Heavy.woff2
  public/assets/fonts/SUIT-Light.otf
  public/assets/fonts/SUIT-Light.woff2
  public/assets/fonts/SUIT-Medium.otf
  public/assets/fonts/SUIT-Medium.woff2
  public/assets/fonts/SUIT-Regular.otf
  public/assets/fonts/SUIT-Regular.woff2
  public/assets/fonts/SUIT-SemiBold.otf
  public/assets/fonts/SUIT-SemiBold.woff2
  public/assets/fonts/SUIT-Thin.otf
  public/assets/fonts/SUIT-Thin.woff2
  src/components/form/Textarea/index.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  styles/globals.css
Labels: size/L

#148 프로덕션 배포
  package.json
  pages/detail/index.tsx
  public/assets/fonts/SUIT-Bold.otf
  public/assets/fonts/SUIT-Bold.woff2
  public/assets/fonts/SUIT-ExtraBold.otf
  public/assets/fonts/SUIT-ExtraBold.woff2
  public/assets/fonts/SUIT-ExtraLight.otf
  public/assets/fonts/SUIT-ExtraLight.woff2
  public/assets/fonts/SUIT-Heavy.otf
  public/assets/fonts/SUIT-Heavy.woff2
  public/assets/fonts/SUIT-Light.otf
  public/assets/fonts/SUIT-Light.woff2
  public/assets/fonts/SUIT-Medium.otf
  public/assets/fonts/SUIT-Medium.woff2
  public/assets/fonts/SUIT-Regular.otf
  public/assets/fonts/SUIT-Regular.woff2
  public/assets/fonts/SUIT-SemiBold.otf
  public/assets/fonts/SUIT-SemiBold.woff2
  public/assets/fonts/SUIT-Thin.otf
  public/assets/fonts/SUIT-Thin.woff2
  public/assets/icon/icon-back.svg
  public/assets/icon/icon-logo-mobile.svg
  public/assets/icon/icon-logo.svg
  public/assets/icon/icon-member.svg
  public/assets/icon/icon-menu.svg
  public/assets/icon/icon-profile.svg
  public/assets/svg/question_mark.svg
  src/components/form/Textarea/index.tsx
  src/components/header/Header.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/modal/ModalBackground.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupList/Card/index.tsx
  src/components/page/groupManagement/ItemDescriptionBox.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/utils/date.ts
  stitches.config.ts
  styles/globals.css
  yarn.lock
Labels: size/XXL
