Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-06, with the labels that each got.

#329 공지사항 기능 추가
  pages/detail/index.tsx
  pages/index.tsx
  public/assets/svg/ic.svg
  src/api/notice/hooks.ts
  src/api/notice/index.ts
  src/components/disclosure/Disclosure.tsx
  src/components/page/meetingList/Slider/NoticeSlider/DotWrapper.tsx
  src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx
  src/components/util/parseTextToLink.tsx
Labels: size/L

#339 플레이그라운드 헤더 패키지 업데이트
  package.json
  yarn.lock
Labels: size/S

#342 Revert "공지사항 기능 추가 (#329)"
  pages/detail/index.tsx
  pages/index.tsx
  public/assets/svg/ic.svg
  src/api/notice/hooks.ts
  src/api/notice/index.ts
  src/components/disclosure/Disclosure.tsx
  src/components/page/meetingList/Slider/NoticeSlider/DotWrapper.tsx
  src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx
  src/components/util/parseTextToLink.tsx
Labels: size/L

#343 모바일 카드 컴포넌트 제작
  pages/_app.tsx
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  src/components/filter/MultiSelect/BottomSheet.tsx
  src/components/filter/MultiSelect/SelectComboBoxItem.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/BaseSelect/BaseSelect.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/form/TextInput/index.tsx
  src/components/header/Header.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/page/meetingDetail/ApplicationModalContent.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/MentorTooltip.tsx
  src/components/page/meetingDetail/NextArrow.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingDetail/RecruitmentStatusModalContent.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
  src/components/page/meetingList/Card/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/MobileSize/index.tsx
  src/components/page/meetingList/Card/Skeleton.tsx
  src/components/page/meetingList/Card/Skeleton/MobileSize/CardType.tsx
  src/components/page/meetingList/Card/Skeleton/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/Skeleton/MobileSize/index.tsx
  src/components/page/meetingList/Card/Skeleton/index.tsx
  src/components/page/meetingList/Card/Status.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/EmptyView.tsx
  src/components/page/meetingList/Filter/Modal/BottomSheet/index.tsx
  src/components/page/meetingList/Filter/Modal/Chip/ChipItem.tsx
  src/components/page/meetingList/Filter/Modal/Chip/index.tsx
  src/components/page/meetingList/Filter/Modal/OpenButton.tsx
  src/components/page/meetingList/Filter/Modal/Toggle/index.tsx
  src/components/page/meetingList/Filter/Modal/index.tsx
  src/components/page/meetingList/Filter/Result/InitializationButton.tsx
  src/components/page/meetingList/Filter/Result/ResultItem.tsx
  src/components/page/meetingList/Filter/Result/index.tsx
  src/components/page/meetingList/Filter/Search/index.tsx
  src/components/page/meetingList/Filter/index.tsx
  src/components/page/meetingList/Grid/Layout.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingList/Pagination.tsx
  src/components/page/meetingManagement/ItemDescriptionBox.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/ManagementListSkeleton.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  src/components/page/meetingManagement/MeetingInformationSkeleton.tsx
  src/components/tabList/TabList.tsx
  src/components/util/Divider.tsx
  stitches.config.ts
Labels: size/XXL

#344 Revert "Revert "공지사항 기능 추가 (#329)""
  pages/detail/index.tsx
  pages/index.tsx
  public/assets/svg/ic.svg
  src/api/notice/hooks.ts
  src/api/notice/index.ts
  src/components/disclosure/Disclosure.tsx
  src/components/page/meetingList/Slider/NoticeSlider/DotWrapper.tsx
  src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx
  src/components/util/parseTextToLink.tsx
Labels: size/L
