Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-07, with the labels that each got.

#351 프로덕션 배포
  pages/_app.tsx
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  src/components/filter/MultiSelect/BottomSheet.tsx
  src/components/filter/MultiSelect/SelectComboBoxItem.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/BaseSelect/BaseSelect.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/form/TextInput/index.tsx
  src/components/header/Header.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/page/meetingDetail/ApplicationModalContent.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/MentorTooltip.tsx
  src/components/page/meetingDetail/NextArrow.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingDetail/RecruitmentStatusModalContent.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
  src/components/page/meetingList/Card/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/MobileSize/index.tsx
  src/components/page/meetingList/Card/Skeleton.tsx
  src/components/page/meetingList/Card/Skeleton/MobileSize/CardType.tsx
  src/components/page/meetingList/Card/Skeleton/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/Skeleton/MobileSize/index.tsx
  src/components/page/meetingList/Card/Skeleton/index.tsx
  src/components/page/meetingList/Card/Status.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/EmptyView.tsx
  src/components/page/meetingList/Filter/Modal/BottomSheet/index.tsx
  src/components/page/meetingList/Filter/Modal/Chip/ChipItem.tsx
  src/components/page/meetingList/Filter/Modal/Chip/index.tsx
  src/components/page/meetingList/Filter/Modal/OpenButton.tsx
  src/components/page/meetingList/Filter/Modal/Toggle/index.tsx
  src/components/page/meetingList/Filter/Modal/index.tsx
  src/components/page/meetingList/Filter/Result/InitializationButton.tsx
  src/components/page/meetingList/Filter/Result/ResultItem.tsx
  src/components/page/meetingList/Filter/Result/index.tsx
  src/components/page/meetingList/Filter/Search/index.tsx
  src/components/page/meetingList/Filter/index.tsx
  src/components/page/meetingList/Grid/Layout.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingList/Pagination.tsx
  src/components/page/meetingManagement/ItemDescriptionBox.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/ManagementListSkeleton.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  src/components/page/meetingManagement/MeetingInformationSkeleton.tsx
  src/components/tabList/TabList.tsx
  src/components/util/Divider.tsx
  stitches.config.ts
Labels: size/XXL

#349 스토리북 셋업
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  yarn.lock
Labels: size/XXL

#352 피드, 모임 안내 탭 추가
  pages/detail/index.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/FeedPanel.tsx
  src/components/page/meetingDetail/InformationPanel.tsx
  src/components/tabList/TabList.tsx
Labels: size/L

#354 헤더 업데이트
  package.json
  yarn.lock
Labels: size/S

#357 피드 탭 empty view 추가
  pages/detail/index.tsx
  src/components/page/meetingDetail/FeedPanel.tsx
Labels: size/M

#355 프로덕션 배포
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pages/detail/index.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/FeedPanel.tsx
  src/components/page/meetingDetail/InformationPanel.tsx
  src/components/tabList/TabList.tsx
  yarn.lock
Labels: size/XXL

#359 간단한 UI 개선사항 반영
  src/components/page/meetingDetail/InformationPanel.tsx
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
Labels: size/XS

#360 프로덕션 배포
  src/components/page/meetingDetail/InformationPanel.tsx
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
Labels: size/XS

#350 아바타 컴포넌트 구현
  src/components/avatar/Avatar.stories.ts
  src/components/avatar/Avatar.tsx
  src/components/avatar/AvatarGroup.stories.tsx
  src/components/avatar/AvatarGroup.tsx
Labels: size/L
