Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-09, with the labels that each got.

#363 Open API Specification 코드젠 스크립트 및 스키마 추가
  .eslintignore
  .gitignore
  package.json
  src/__generated__/schema.d.ts
  src/api/index.ts
  tsconfig.json
  yarn.lock
Labels: size/M

#369 피드 컴포넌트 구조화 및 스타일링
  README.md
  pages/detail/index.tsx
  public/assets/svg/like_active.svg
  public/assets/svg/like_default.svg
  public/assets/svg/more.svg
  public/favicon.ico
  src/components/page/meetingDetail/Feed/EmptyView.tsx
  src/components/page/meetingDetail/Feed/FeedItem.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/meetingDetail/Feed/Skeleton/DesktopFeedListSkeleton.tsx
  src/components/page/meetingDetail/Feed/Skeleton/FeedItemSkeleton.tsx
  src/components/page/meetingDetail/Feed/Skeleton/MobileFeedListSkeleton.tsx
  src/components/page/meetingDetail/FeedPanel.tsx
  src/components/page/meetingDetail/Information/InformationPanel.tsx
  stitches.config.ts
Labels: size/XL

#385 Avatar 컴포넌트 Overlay 인터페이스 추가
  src/components/avatar/Avatar.tsx
Labels: size/XS

#365 피드 상세 뷰어 컴포넌트 뼈대 작성
  .storybook/main.ts
  .storybook/preview.ts
  public/assets/svg/comment.svg
  public/assets/svg/ic_menu.svg
  public/assets/svg/like.svg
  public/assets/svg/like_fill.svg
  src/components/feed/FeedPostViewer/FeedPostViewer.stories.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/L

#371 피드 상세 뷰어 컴포넌트 스타일링 - 콘텐츠 영역
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/L

#373 피드 상세 댓글 좋아요 영역 추가
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/M

#375 피드 상세 뷰어 컴포넌트 댓글 입력 UI 추가
  public/assets/svg/send.svg
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/M

#391 feat: tab의 생명력을 앗아가다!
  pages/index.tsx
  src/components/tabList/TabList.tsx
Labels: size/XS

#389 boxSizing:border-box 일괄 적용 작업
  src/components/filter/MultiSelect/index.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetButton.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetDialog.tsx
  src/components/form/Select/Button/index.tsx
  src/components/form/Select/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Filter/Modal/OpenButton.tsx
  src/components/page/meetingList/Filter/Search/index.tsx
  styles/globals.css
Labels: size/M

#376 피드 생성 폼 퍼블리싱 완성
  pages/_app.tsx
  pages/detail/index.tsx
  public/assets/svg/arrow_down.svg
  public/assets/svg/camera.svg
  src/components/disclosure/Disclosure.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/modal/ModalContainer.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedModal/FeedCreateModal.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedModal/FeedFormPresentation.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedModal/ImagePreview/index.tsx
  src/components/util/Divider.tsx
  src/hooks/useOverlay/Index.tsx
  src/hooks/useOverlay/OverlayController.tsx
  src/hooks/useOverlay/OverlayProvider.tsx
  src/hooks/useOverlay/types.ts
  stitches.config.ts
Labels: size/XL

#403 SVG 크기 설정을 위한 next.config.js 수정
  next.config.js
  src/types/svg.d.ts
Labels: size/S

#381 피드 생성 스키마 정의
  pages/detail/index.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedCreateModal.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedFormPresentation.tsx
  src/components/page/meetingDetail/Feed/Modal/ImagePreview/index.tsx
  src/components/page/meetingDetail/Feed/Modal/schema.ts
Labels: size/M

#387 피드 생성 폼 컨펌 모달 적용 및 formController 적용
  pages/detail/index.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedCreateModal.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedFormPresentation.tsx
Labels: size/M

#407 피드 상세 뷰 이미지 영역 추가
  src/components/feed/FeedPostViewer/FeedPostViewer.stories.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/M

#393 토스트 메세지를 만들어 봅시다
  public/assets/svg/caution.svg
  src/components/page/meetingDetail/Feed/Modal/FeedCreateModal.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedFormPresentation.tsx
  src/components/page/meetingDetail/Feed/Modal/schema.ts
  src/hooks/useToast/Toast.tsx
  src/hooks/useToast/index.tsx
Labels: size/L

#409 피드 상세 뷰 이미지 캐러셀 UI 추가
  .storybook/preview.tsx
  package.json
  src/components/feed/FeedPostViewer/FeedPostViewer.stories.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/modal/ImageCarouselModal.tsx
  yarn.lock
Labels: size/L

#402 보라빛이 왜 죽음을 암시했는지 알게 됨
  package.json
  pages/index.tsx
  public/assets/svg/check.svg
  public/assets/svg/checkBox/selected.svg
  public/assets/svg/icon_progress_checked.svg
  public/assets/svg/plus.svg
  public/assets/svg/profile_default.svg
  public/assets/svg/radio/selected.svg
  public/assets/svg/send.svg
  src/components/button/Switch.tsx
  src/components/filter/MultiSelect/BottomSheet.tsx
  src/components/form/CheckBox/NeedMentor.tsx
  src/components/form/Presentation/ImagePreview/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/OptionItem/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/loader/Loader.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/page/meetingDetail/ApplicationModalContent.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
  src/components/page/meetingList/Card/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/Status.tsx
  src/components/page/meetingList/Filter/Modal/Chip/ChipItem.tsx
  src/components/page/meetingList/Filter/index.tsx
  src/components/page/meetingList/Pagination.tsx
  src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  stitches.config.ts
  yarn.lock
Labels: size/L

#396 피드 생성 api 를 연결 해보자
  pages/detail/index.tsx
  src/api/post/index.ts
  src/components/page/meetingDetail/Feed/Modal/FeedCreateModal.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedFormPresentation.tsx
Labels: size/M

#399 피드 생성뷰 모바일 딱대
  public/assets/svg/x_big_gray.svg
  src/components/page/meetingDetail/Feed/Modal/FeedCreateModal.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedFormPresentation.tsx
  src/hooks/useToast/Toast.tsx
Labels: size/L

#398 피드 상세 content 부분 모바일 대응
  src/components/avatar/Avatar.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/M

#412 피드 상세 댓글 좋아요 영역 UI 구현 방식 수정과 모바일 대응
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/XXL, size/S

#410 OG 관련 설정
  pages/_app.tsx
  public/assets/images/thumbnail.jpg
  src/components/seo/SEO.tsx
Labels: size/M

#416 피드 상세 뷰 이미지 영역 및 캐러셀 반응형 디자인 추가
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/modal/ImageCarouselModal.tsx
Labels: size/S

#420 피드 상세 뷰 게시글 조회 API 연동
  pages/post/index.tsx
Labels: size/S

#423 피드 상세 뷰 게시글 작성 시간 포맷 수정
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/XS

#426 og:image가 안 보이는 문제
  src/components/seo/SEO.tsx
Labels: size/XS

#434 주말 아침부터 보라빛 향기
  package.json
  pages/detail/index.tsx
  src/components/button/Switch.tsx
  yarn.lock
Labels: size/XL

#436 피드 작성 버튼 임시 제거 및 주석 처리
  pages/detail/index.tsx
  src/components/page/meetingDetail/Feed/EmptyView.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/S

#437 제목 minHeight 설정
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
Labels: size/XS

#438 프로덕션 배포
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
Labels: size/XS

#429 모임 피드 아이템 보완
  src/components/avatar/Avatar.tsx
  src/components/page/meetingDetail/Feed/FeedItem.tsx
  src/constants/feed.ts
  src/constants/index.ts
  src/utils/truncateText.ts
  stitches.config.ts
Labels: size/M

#441 배포를 위해 주석 처리하거나 제거했던 코드 되살리기
  pages/detail/index.tsx
  src/components/page/meetingDetail/Feed/EmptyView.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
Labels: size/M

#427 모달 관련 오류 해결
  pages/detail/index.tsx
  src/components/modal/ModalBackground.tsx
  src/components/page/meetingDetail/Feed/EmptyView.tsx
  src/components/page/meetingDetail/Feed/Modal/FeedCreateModal.tsx
  src/hooks/useOverlay/Index.tsx
  src/hooks/useOverlay/OverlayController.tsx
  src/hooks/useOverlay/OverlayProvider.tsx
Labels: size/L

#382 피드 상세 뷰 댓글 UI 추가
  .storybook/main.ts
  public/assets/svg/like_fill_in_comment.svg
  public/assets/svg/like_in_comment.svg
  src/components/feed/FeedCommentViewer/FeedCommentViewer.stories.ts
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
Labels: size/L

#443 인증토큰 적용 방법 수정 및 opanapi-fetch 가 codegen 한 api 클라이언트에 인증 토큰 적용
  package.json
  pages/_app.tsx
  pages/post/index.tsx
  src/api/index.ts
  src/components/util/auth.ts
  src/stores/tokenStore.ts
  yarn.lock
Labels: size/M

#444 피드 상세 조회 페이지에 댓글 작성 API 연동
  pages/post/index.tsx
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/L

#449 피드 상세 페이지 댓글 목록 조회 API 연동
  pages/post/index.tsx
  src/components/feed/FeedCommentInput/FeedCommentInput.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/utils/dayjs.ts
Labels: size/M

#452 masonry 레이아웃 적용
  package.json
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  yarn.lock
Labels: size/L

#451 피드 상세 좋아요 이벤트 추가
  .storybook/preview.tsx
  package.json
  pages/post/index.tsx
  public/assets/svg/comment.svg
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  yarn.lock
Labels: size/L

#456 피드 상세 뷰 댓글 목록 무한스크롤 적용
  pages/post/index.tsx
  src/hooks/useComment.ts
Labels: size/M

#461 피드 상세 뷰 댓글 좋아요 API 연동
  pages/post/index.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
  src/hooks/useComment/useComment.ts
  src/hooks/useComment/useCommentMutation.ts
Labels: size/M

#468 피드 목록 조회 API 인증 안되는 이슈 수정
  src/api/post/index.ts
Labels: size/XS

#450 피드 개수 보여주는 부분 추가
  package.json
  src/api/post/hooks.ts
  src/components/page/meetingDetail/Feed/EmptyView.tsx
  src/components/page/meetingDetail/Feed/FeedItem.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/constants/feed.ts
  yarn.lock
Labels: size/L

#471 피드 상세 뷰 댓글 개수 정확히 보여주도록 수정
  pages/post/index.tsx
Labels: size/XS

#462 style: 댓글 삭제 모달 컴포넌트 추가
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
Labels: size/S

#463 댓글 삭제 API 연동
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
Labels: size/M

#467 피드 상세 뷰 댓글 액션 합성할 수 있도록 수정
  pages/post/index.tsx
  src/api/post/hooks.ts
  src/components/feed/FeedActionButton/FeedActionButton.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
Labels: size/L

#465 피드 수정뷰 제작
  pages/_app.tsx
  pages/post/index.tsx
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/feed/Modal/ImagePreview/index.tsx
  src/components/feed/Modal/feedSchema.ts
  src/components/page/meetingDetail/Feed/EmptyView.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/constants/feed.ts
  src/hooks/useOverlay/OverlayProvider.tsx
  tsconfig.json
Labels: size/L

#480 모바일 주소창으로 인해 완료버튼 안보이는 이슈
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedEditModal.tsx
Labels: size/XS

#475 schema generation 스크립트가 리모트 OAS 스펙을 가져오도록 수정
  package.json
  src/__generated__/schema.d.ts
Labels: size/XS

#482 댓글 수정 기능 추가
  pages/post/index.tsx
  src/__generated__/schema.d.ts
  src/api/post/hooks.ts
  src/components/feed/FeedActionButton/FeedActionButton.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentEditor/FeedCommentEditor.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.stories.ts
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.stories.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/hooks/useComment/useComment.ts
  src/hooks/useComment/useCommentMutation.ts
Labels: size/L
