Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-05, with the labels that each got.

#313 모임 생성/수정 시 '행사' 카테고리 선택할 수 있도록 추가
  src/data/categories.ts
Labels: size/XS

#315 모비일 검색창에 취소가 가려지는 이슈
  src/components/page/meetingList/Filter/Search/Mobile.tsx
Labels: size/XS

#319 Sentry 설정 추가
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  next.config.js
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  yarn.lock
Labels: size/XXL

#316 프로덕션 배포
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  next.config.js
  package.json
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/components/page/meetingList/Filter/Search/Mobile.tsx
  src/data/categories.ts
  yarn.lock
Labels: size/XXL

#320 모임 신청자 리스트 디자인 수정사항 반영
  src/api/user/index.ts
  src/components/page/meetingManagement/ItemDescriptionBox.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/constants/font.ts
  stitches.config.ts
Labels: size/L

#321 현재 로그인한 유저 프로필 조회하는 크루 API 연동
  pages/_app.tsx
  pages/index.tsx
  src/api/members/hooks.ts
  src/api/members/index.ts
  src/api/members/type.ts
  src/api/user/hooks.ts
  src/api/user/index.ts
  src/components/header/Header.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
Labels: size/M

#322 프로덕션 배포
  pages/_app.tsx
  pages/index.tsx
  src/api/members/hooks.ts
  src/api/members/index.ts
  src/api/members/type.ts
  src/api/user/hooks.ts
  src/api/user/index.ts
  src/components/header/Header.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingManagement/ItemDescriptionBox.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/constants/font.ts
  stitches.config.ts
Labels: size/L

#323 프로덕션 배포
  src/components/page/meetingManagement/ManagementListItem.tsx
Labels: size/XS

#324 프로덕션 배포
  src/components/page/meetingManagement/ManagementListItem.tsx
Labels: size/XS

#326 초대하기 관련 코드 제거
  pages/detail/index.tsx
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingManagement/InvitationListItem.tsx
  src/components/page/meetingManagement/InvitationModal/InvitationModal.tsx
  src/components/page/meetingManagement/InvitationModal/SelectUsersStep.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/constants/option.ts
Labels: size/XL

#333 새로운 컬러 추가
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  src/components/button/Arrow.tsx
  src/components/button/Switch.tsx
  src/components/filter/MultiSelect/BottomSheet.tsx
  src/components/filter/MultiSelect/SelectComboBoxItem.tsx
  src/components/filter/MultiSelect/SelectRadioItem.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/form/FormSwitch/FormSwitch.tsx
  src/components/form/Label/index.tsx
  src/components/form/Presentation/ImagePreview/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetButton.tsx
  src/components/form/Select/Button/index.tsx
  src/components/form/Select/OptionItem/CheckboxOptionItem.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/form/TextInput/index.tsx
  src/components/form/Textarea/index.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/page/meetingDetail/ApplicationModalContent.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/NextArrow.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingDetail/RecruitmentStatusModalContent.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Filter/Modal/Chip/ChipItem.tsx
  src/components/page/meetingList/Filter/Modal/Chip/index.tsx
  src/components/page/meetingList/Filter/Modal/OpenButton.tsx
  src/components/page/meetingList/Filter/Modal/Toggle/index.tsx
  src/components/page/meetingList/Filter/Result/InitializationButton.tsx
  src/components/page/meetingList/Filter/Result/ResultItem.tsx
  src/components/page/meetingList/Filter/Search/Mobile.tsx
  src/components/page/meetingList/Filter/Search/index.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  src/components/tabList/TabList.tsx
  stitches.config.ts
Labels: size/L

#335 미디어 쿼리 분기점 수정
  src/components/page/meetingDetail/DetailHeader.tsx
  src/constants/url.ts
  src/hooks/useDisplay.ts
Labels: size/XS

#331 새로운 폰트 스타일 추가
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  src/components/button/Arrow.tsx
  src/components/button/Switch.tsx
  src/components/filter/MultiSelect/BottomSheet.tsx
  src/components/filter/MultiSelect/SelectComboBoxItem.tsx
  src/components/filter/MultiSelect/SelectRadioItem.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/form/FormSwitch/FormSwitch.tsx
  src/components/form/Label/index.tsx
  src/components/form/Presentation/ImagePreview/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetButton.tsx
  src/components/form/Select/Button/index.tsx
  src/components/form/Select/OptionItem/CheckboxOptionItem.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/form/TextInput/index.tsx
  src/components/form/Textarea/index.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/page/meetingDetail/ApplicationModalContent.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/NextArrow.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingDetail/RecruitmentStatusModalContent.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Filter/Modal/Chip/ChipItem.tsx
  src/components/page/meetingList/Filter/Modal/Chip/index.tsx
  src/components/page/meetingList/Filter/Modal/OpenButton.tsx
  src/components/page/meetingList/Filter/Modal/Toggle/index.tsx
  src/components/page/meetingList/Filter/Result/InitializationButton.tsx
  src/components/page/meetingList/Filter/Result/ResultItem.tsx
  src/components/page/meetingList/Filter/Search/Mobile.tsx
  src/components/page/meetingList/Filter/Search/index.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  src/components/tabList/TabList.tsx
  src/constants/font.ts
  stitches.config.ts
  styles/globals.css
Labels: size/L

#337 디자인 시스템 수정사항 반영
  pages/index.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Grid/Layout.tsx
  src/components/page/meetingList/Pagination.tsx
  src/components/tabList/TabList.tsx
Labels: size/M
