Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-11, with the labels that each got.

#577 프로덕션 배포
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/form/Presentation/index.tsx
  src/types/form.ts
Labels: size/S

#580 localStorage 대신 sessionStorage 사용
  src/components/util/auth.ts
Labels: size/XS

#581 프로덕션 배포
  src/components/util/auth.ts
Labels: size/XS

#589 모임 피드 게시글 신고하기 기능 추가
  pages/post/index.tsx
  src/components/feed/FeedActionButton/FeedActionButton.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/hooks/useToast/Toast.tsx
Labels: size/L

#591 CODEOWNERS 추가
  .github/CODEOWNERS
Labels: size/XS
