Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-04, with the labels that each got.

#285 모임 승인 시 alert 처리 보완
  pages/index.tsx
  src/api/meeting/hooks.ts
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingList/Grid/Layout.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/utils/alertErrorMessage.ts
Labels: size/L

#286 프로덕션 배포
  pages/index.tsx
  src/api/meeting/hooks.ts
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingList/Grid/Layout.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/utils/alertErrorMessage.ts
Labels: size/L

#287 CI환경 빌드 커맨드 수정으로 빌드 시간 오래걸리는 것 개선
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  package.json
  yarn.lock
Labels: size/L

#289 모임 생성/수정 페이지 신규 이미지 업로드 API 연동
  pages/edit/index.tsx
  pages/make/index.tsx
  src/api/meeting/index.ts
  src/components/form/FileInput/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/constants/url.ts
  src/types/form.ts
  src/utils/urlToFile.ts
Labels: size/L

#293 채널톡 연동
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  pages/_app.tsx
  src/utils/ChannelService.ts
Labels: size/L

#294 배포 github action 수정
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: size/S

#291 프로덕션 배포
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  License
  package.json
  pages/_app.tsx
  pages/edit/index.tsx
  pages/make/index.tsx
  src/api/meeting/index.ts
  src/components/form/FileInput/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/constants/url.ts
  src/types/form.ts
  src/utils/ChannelService.ts
  src/utils/urlToFile.ts
  yarn.lock
Labels: size/XL

#296 Revert "Merge pull request #291 from sopt-makers/develop"
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  License
  package.json
  pages/_app.tsx
  pages/edit/index.tsx
  pages/make/index.tsx
  src/api/meeting/index.ts
  src/components/form/FileInput/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/constants/url.ts
  src/types/form.ts
  src/utils/ChannelService.ts
  src/utils/urlToFile.ts
  yarn.lock
Labels: size/XL

#298 빌드 커맨드 수정
  package.json
  yarn.lock
Labels: size/L

#299 프로덕션 배포
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  package.json
  yarn.lock
Labels: size/L

#300 build: edit deploy ci job to publish out directory
  .github/workflows/deploy-production.yml
Labels: size/XS

#301 프로덕션 배포
  .github/workflows/deploy-production.yml
Labels: size/XS

#302 Revert "Revert "Merge pull request #291 from sopt-makers/develop""
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  License
  pages/_app.tsx
  pages/edit/index.tsx
  pages/make/index.tsx
  src/api/meeting/index.ts
  src/components/form/FileInput/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/constants/url.ts
  src/types/form.ts
  src/utils/ChannelService.ts
  src/utils/urlToFile.ts
Labels: size/XL

#303 프로덕션 배포
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  License
  pages/_app.tsx
  pages/edit/index.tsx
  pages/make/index.tsx
  src/api/meeting/index.ts
  src/components/form/FileInput/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/constants/url.ts
  src/types/form.ts
  src/utils/ChannelService.ts
  src/utils/urlToFile.ts
Labels: size/XL

#305 Feat/#304
  pages/_app.tsx
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/management/index.tsx
  src/api/meeting/index.ts
  src/components/form/CheckBox/NeedMentor.tsx
  src/components/form/FileInput/index.tsx
  src/components/form/Presentation/ImagePreview/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/header/Header.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingDetail/RecruitmentStatusModalContent.tsx
  src/components/page/meetingList/Card/Status.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingManagement/InvitationModal/InvitationModal.tsx
  src/components/page/meetingManagement/InvitationModal/SelectUsersStep.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  src/components/util/auth.ts
  src/constants/option.ts
  tsconfig.json
Labels: size/M

#306 프로덕션 배포
  pages/_app.tsx
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/management/index.tsx
  src/api/meeting/index.ts
  src/components/form/CheckBox/NeedMentor.tsx
  src/components/form/FileInput/index.tsx
  src/components/form/Presentation/ImagePreview/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/header/Header.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingDetail/RecruitmentStatusModalContent.tsx
  src/components/page/meetingList/Card/Status.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingManagement/InvitationModal/InvitationModal.tsx
  src/components/page/meetingManagement/InvitationModal/SelectUsersStep.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  src/components/util/auth.ts
  src/constants/option.ts
  tsconfig.json
Labels: size/M

#307 csv 다운로드 버튼 생성
  pages/_app.tsx
  pages/mine/management/index.tsx
  public/assets/svg/download.svg
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
Labels: size/L

#308 프로덕션 배포
  pages/_app.tsx
  pages/mine/management/index.tsx
  public/assets/svg/download.svg
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
Labels: size/L

#311 계정 정보 없는 경우 처리 (#310)
  README.md
  src/components/util/auth.ts
Labels: size/S
