Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2023-03, with the labels that each got.

#151 모임 신청 가이드 버튼 추가
  src/components/page/groupList/Filter/Search/index.tsx
  src/components/page/groupList/Filter/index.tsx
Labels: size/M

#152 프로덕션 배포
  src/components/header/Header.tsx
  src/components/page/groupDetail/Carousel.tsx
  src/components/page/groupList/Filter/Search/index.tsx
  src/components/page/groupList/Filter/index.tsx
Labels: size/M

#153 모임 상세 페이지 디자인 수정사항 반영
  pages/detail/index.tsx
  pages/index.tsx
  src/components/page/groupDetail/Carousel.tsx
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/tabList/TabList.tsx
  src/constants/font.ts
  src/constants/link.ts
Labels: size/M

#166 모집 현황 모달 디자인 수정사항 반영
  src/components/page/groupDetail/DetailHeader.tsx
  src/components/page/groupDetail/RecruitmentStatusList.tsx
  src/components/page/groupList/Filter/index.tsx
  src/components/page/groupManagement/GroupInformation.tsx
  src/components/page/groupManagement/ManagementListItem.tsx
  src/constants/option.ts
  stitches.config.ts
Labels: size/L

#161 type definition 파일 위치 통일
  shim-svg.d.ts
  src/types/svg.d.ts
Labels: size/XS

#160 사용중인 모든 group 단어를 meeting 으로 변경
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  src/api/group.ts
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/api/user/hooks.ts
  src/api/user/index.ts
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/NextArrow.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/Skeleton.tsx
  src/components/page/meetingList/Card/Status.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/EmptyView.tsx
  src/components/page/meetingList/Filter/Result/InitializationButton.tsx
  src/components/page/meetingList/Filter/Result/ResultItem.tsx
  src/components/page/meetingList/Filter/Result/index.tsx
  src/components/page/meetingList/Filter/Search/Mobile.tsx
  src/components/page/meetingList/Filter/Search/index.tsx
  src/components/page/meetingList/Filter/Select/index.tsx
  src/components/page/meetingList/Filter/index.tsx
  src/components/page/meetingList/Grid/Layout.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingList/Pagination.tsx
  src/components/page/meetingManagement/Filter/index.tsx
  src/components/page/meetingManagement/InvitationListItem.tsx
  src/components/page/meetingManagement/InvitationModal/InvitationModal.tsx
  src/components/page/meetingManagement/InvitationModal/SelectUsersStep.tsx
  src/components/page/meetingManagement/ItemDescriptionBox.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/ManagementListSkeleton.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  src/components/page/meetingManagement/MeetingInformationSkeleton.tsx
Labels: size/XL

#140 feat: 모임 생성 시 작성 안한 항목있을 때 모임 개설 버튼 비활성화
  pages/make/index.tsx
  src/components/form/Presentation/index.tsx
  src/types/form.ts
Labels: size/S

#162 모임 생성 / 수정 페이지 react-query 적용
  pages/edit/index.tsx
  pages/make/index.tsx
Labels: size/S

#170 초대하기 버튼 숨기기
  pages/mine/management/index.tsx
  src/components/page/meetingList/Filter/Result/InitializationButton.tsx
Labels: size/M

#163 useMultiSelect 제작
  src/components/filter/MultiSelect/index.tsx
  src/components/page/meetingList/Filter/Select/index.tsx
  src/hooks/queryString/index.ts
  src/hooks/useSelect.ts
Labels: size/M

#164 Pagination 반응형 적용
  src/components/button/Arrow.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/page/meetingList/Pagination.tsx
  src/types/svg.d.ts
Labels: size/M

#172 프로덕션 배포
  package.json
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/index.tsx
  pages/make/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  shim-svg.d.ts
  src/api/group.ts
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/api/user/hooks.ts
  src/api/user/index.ts
  src/components/button/Arrow.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/page/meetingDetail/Carousel.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/NextArrow.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/Skeleton.tsx
  src/components/page/meetingList/Card/Status.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/EmptyView.tsx
  src/components/page/meetingList/Filter/Result/InitializationButton.tsx
  src/components/page/meetingList/Filter/Result/ResultItem.tsx
  src/components/page/meetingList/Filter/Result/index.tsx
  src/components/page/meetingList/Filter/Search/Mobile.tsx
  src/components/page/meetingList/Filter/Search/index.tsx
  src/components/page/meetingList/Filter/Select/index.tsx
  src/components/page/meetingList/Filter/index.tsx
  src/components/page/meetingList/Grid/Layout.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingList/Pagination.tsx
  src/components/page/meetingManagement/Filter/index.tsx
  src/components/page/meetingManagement/InvitationListItem.tsx
  src/components/page/meetingManagement/InvitationModal/InvitationModal.tsx
  src/components/page/meetingManagement/InvitationModal/SelectUsersStep.tsx
  src/components/page/meetingManagement/ItemDescriptionBox.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/ManagementListSkeleton.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  src/components/page/meetingManagement/MeetingInformationSkeleton.tsx
  src/components/tabList/TabList.tsx
  src/constants/font.ts
  src/constants/link.ts
  src/constants/option.ts
  src/hooks/queryString/index.ts
  src/hooks/usePlaygroundLink.ts
  src/hooks/useSelect.ts
  src/types/form.ts
  src/types/svg.d.ts
  stitches.config.ts
  yarn.lock
Labels: size/XXL

#176 모임 관리 페이지 로딩 처리 개선
  src/components/page/meetingManagement/ItemDescriptionBox.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
Labels: size/M

#171 모임 생성 / 수정 폼에 '멘토 구해요' 입력 필드 추가
  package.json
  pages/edit/index.tsx
  pages/make/index.tsx
  public/assets/svg/check_need_mentor.svg
  src/api/meeting/index.ts
  src/components/form/CheckBox/NeedMentor.tsx
  src/components/form/Presentation/index.tsx
  src/types/form.ts
  yarn.lock
Labels: size/L

#184 모임 생성 / 수정 페이지 대상 파트 입력 필드 추가
  public/assets/svg/checkBox/unselected.svg
  src/components/filter/MultiSelect/BottomSheet.tsx
  src/components/filter/MultiSelect/SelectRadioItem.tsx
  src/components/form/FormController/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/BaseSelect/BaseSelect.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetButton.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetDialog.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetSelect.tsx
  src/components/form/Select/Button/index.tsx
  src/components/form/Select/OptionItem/CheckboxOptionItem.tsx
  src/components/form/Select/OptionItem/MobileOptionItem.tsx
  src/components/form/Select/OptionItem/index.tsx
  src/components/form/Select/index.tsx
  src/components/form/Select/types/props.ts
  src/components/form/Select/utils/index.ts
  src/data/options.ts
  src/types/form.ts
Labels: size/L

#189 Switch 컴포넌트 추가
  src/components/button/Switch.tsx
Labels: size/M

#191 모임 생성 / 수정 폼에 대상 기수 입력 필드 추가
  src/components/button/Switch.tsx
  src/components/form/FormSwitch/FormSwitch.tsx
  src/components/form/Presentation/index.tsx
  src/types/form.ts
Labels: size/M

#199 api, playgroundApi baseURL 수정
  src/api/index.ts
Labels: size/XS

#198 baseURL에 production 추가
  src/api/index.ts
Labels: size/XS

#202 GTM 적용
  pages/_app.tsx
  pages/_document.tsx
  src/utils/gtm.ts
Labels: size/M

#200 모임 생성 / 수정 '멘토 구해요', '대상 기수', '대상 파트' API 연동
  pages/edit/index.tsx
  src/api/meeting/index.ts
  src/components/form/Presentation/index.tsx
  src/data/options.ts
  src/types/form.ts
Labels: size/M

#205 프로덕션 배포
  pages/_app.tsx
  pages/_document.tsx
  pages/edit/index.tsx
  src/api/index.ts
  src/api/meeting/index.ts
  src/components/button/Arrow.tsx
  src/components/filter/MultiSelect/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/constants/option.ts
  src/data/options.ts
  src/types/form.ts
  src/utils/gtm.ts
Labels: size/L

#208 프로덕션 배포
  src/api/index.ts
Labels: size/XS

#210 프로덕션 배포
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: size/S

#211 프로덕션 배포
  .github/workflows/deploy-production.yml
Labels: size/XS

#212 프로덕션 배포
  .github/workflows/deploy-production.yml
Labels: size/XS

#217 모임 생성 시 체크박스 필드('대상 기수', '멘토 구해요')에 한번 체크해야 제출 버튼 활성화 되는 이슈 수정
  src/components/form/FormController/index.tsx
  src/components/form/Presentation/index.tsx
Labels: size/S

#216 모임 생성 / 수정 시 '대상 파트' 선택 안할 경우 table of content 에서 체크박스 해제
  src/components/form/TableOfContents/index.tsx
Labels: size/XS

#221 자잘한 수정사항 반영
  .github/workflows/deploy-production.yml
  pages/detail/index.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingDetail/RecruitmentStatusList.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Pagination.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
Labels: size/M

#224 프로덕션 배포
  pages/index.tsx
  src/components/page/meetingList/Filter/Result/InitializationButton.tsx
  src/components/page/meetingList/Filter/Search/Mobile.tsx
  src/components/page/meetingList/Filter/Search/index.tsx
Labels: size/XS

#225 프로덕션 배포
  src/components/page/meetingList/Filter/Modal/OpenButton.tsx
Labels: size/XS

#226 프로덕션 배포
  src/components/form/Presentation/index.tsx
Labels: size/XS

#234 chore: 모임 기간 => 활동 기간
  pages/detail/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/page/meetingList/Card/index.tsx
  src/types/form.ts
Labels: size/S

#228 모임 수정 페이지에서 폼이 비어있는 이슈 수정
  pages/edit/index.tsx
Labels: size/S

#230 Safari에서 날짜 입력 시 에러나는 버그 수정
  src/types/form.ts
Labels: size/XS

#235 모집 대상에 따른 모임 신청 버튼 처리
  src/components/page/meetingDetail/DetailHeader.tsx
Labels: size/XS

#236 모임 생성 / 수정 페이지 모집 대상 에러 메시지 수정
  src/components/form/Presentation/index.tsx
  src/types/form.ts
Labels: size/M

#237 프로덕션 배포
  pages/detail/index.tsx
  pages/edit/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingList/Card/index.tsx
  src/types/form.ts
Labels: size/L

#239 구버전 사파리에서 셀렉트박스 선택 안되는 이슈 수정
  src/components/form/Select/BaseSelect/BaseSelect.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetSelect.tsx
Labels: size/XS

#242 디바이스에서 리스트를 두줄로 보이길 원함
  pages/_app.tsx
  src/components/page/meetingList/Filter/Result/index.tsx
  src/components/page/meetingList/Filter/Search/Mobile.tsx
  src/components/page/meetingList/Grid/Layout.tsx
  stitches.config.ts
Labels: size/S

#243 프로덕션 배포
  pages/_app.tsx
  src/components/page/meetingList/Filter/Result/index.tsx
  src/components/page/meetingList/Filter/Search/Mobile.tsx
  src/components/page/meetingList/Grid/Layout.tsx
  stitches.config.ts
Labels: size/S

#245 텍스트를 클릭 가능한 링크로 변환하기
  pages/detail/index.tsx
Labels: size/S

#246 모임 수정 시 글자 수 300자 제한 관련 이슈 해결
  src/components/form/Textarea/index.tsx
Labels: size/XS

#248 fix: heic 확장자 대응
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingList/Card/index.tsx
  src/utils/image.ts
Labels: size/S

#251 모집 정책 관련 임시 변경
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
Labels: size/S

#253 프로덕션 배포
  pages/detail/index.tsx
Labels: size/XS

#257 pagination moveBundle 로직 수정
  src/components/page/meetingList/Pagination.tsx
Labels: size/XS

#258 프로덕션 배포
  README.md
  src/components/page/meetingList/Pagination.tsx
Labels: size/M

#270 모임 신청 취소 시 alert 추가
  src/components/page/meetingDetail/DetailHeader.tsx
Labels: size/XS

#272 모임 개설과 관련된 부분 주석 처리
  pages/index.tsx
Labels: size/M

#268 playground 링크로 이동하는 부분 수정
  README.md
  pages/_app.tsx
  pages/index.tsx
  src/components/header/Header.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/util/auth.ts
  src/hooks/usePlaygroundLink.ts
  src/utils/moveToProfileUploadPage.ts
Labels: size/M

#273 프로덕션 배포
  pages/_app.tsx
  pages/index.tsx
  src/components/header/Header.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/util/auth.ts
  src/hooks/usePlaygroundLink.ts
  src/utils/moveToProfileUploadPage.ts
Labels: size/L

#275 크루 토큰을 로컬 스토리지에 저장하지 않도록 수정
  src/components/util/auth.ts
Labels: size/XS

#279 모임 신청하기 따닥 방지
  src/components/page/meetingDetail/ApplicationModalContent.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
Labels: size/S

#280 프로덕션 배포
  src/components/page/meetingDetail/ApplicationModalContent.tsx
  src/components/page/meetingDetail/DetailHeader.tsx
Labels: size/S

#282 모집 인원 충족 시 처리
  src/api/meeting/hooks.ts
Labels: size/XS

#283 프로덕션 배포
  src/api/meeting/hooks.ts
Labels: size/XS
