Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2024-09, with the labels that each got.

#834 멘션 QA
  src/components/feed/Mention/index.tsx
Labels: size/XS

#836 프러덕션 배포
  src/components/feed/Mention/index.tsx
Labels: size/XS

#837 코드 리뷰어 변경
  .github/CODEOWNERS
  .github/workflows/AutomaticAssignReviewer.yml
Labels: size/XS

#838 프러덕션 배포
  .github/CODEOWNERS
  .github/workflows/AutomaticAssignReviewer.yml
Labels: size/XS

#844 톡문의 위치조정
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  src/components/page/meetingList/Grid/List.tsx
Labels: size/S

#850 모임 피드 쪽 광고 구좌 amplitude 추가
  .yarn/install-state.gz
  ampli.json
  package.json
  src/__generated__/schema2.d.ts
  src/ampli/index.ts
  src/components/page/meetingList/Advertisement/AdCarousel.tsx
  yarn.lock
Labels: size/XXL

#854 내모임, 공지사항 api 마이그레이션
  .yarn/install-state.gz
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/API_LEGACY/user/hooks.ts
  src/api/API_LEGACY/user/index.ts
  src/api/notice/hooks.ts
  src/api/notice/index.ts
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
  src/components/page/meetingList/Card/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/MobileSize/index.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx
Labels: size/M

#853 API 마이그레이션
  pages/_app.tsx
  pages/post/index.tsx
  src/__generated__/schema2.d.ts
  src/api/API_LEGACY/user/hooks.ts
  src/api/API_LEGACY/user/index.ts
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
Labels: size/M

#849 [Feat/#848] 광고 구좌 캐러셀 dot botton 색상 변경
  .eslintrc.json
  .gitignore
  .yarn/install-state.gz
  pages/post/index.tsx
  src/components/page/meetingList/Advertisement/AdCarouselDotBtn.tsx
Labels: size/M

#852 전체 모임 쪽 광고 구좌 amplitude 추가
  .yarn/install-state.gz
  src/components/page/meetingList/Grid/List.tsx
Labels: size/M

#858 프러덕션 배포
  .eslintrc.json
  .gitignore
  .yarn/install-state.gz
  ampli.json
  package.json
  pages/_app.tsx
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  pages/post/index.tsx
  src/__generated__/schema2.d.ts
  src/ampli/index.ts
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/API_LEGACY/user/hooks.ts
  src/api/API_LEGACY/user/index.ts
  src/api/notice/hooks.ts
  src/api/notice/index.ts
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/page/meetingList/Advertisement/AdCarousel.tsx
  src/components/page/meetingList/Advertisement/AdCarouselDotBtn.tsx
  src/components/page/meetingList/Advertisement/index.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
  src/components/page/meetingList/Card/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/MobileSize/index.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx
  yarn.lock
Labels: size/XXL

#859 Revert "프러덕션 배포"_ubuntu issue
  .eslintrc.json
  .gitignore
  .yarn/install-state.gz
  ampli.json
  package.json
  pages/_app.tsx
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  pages/post/index.tsx
  src/__generated__/schema2.d.ts
  src/ampli/index.ts
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/API_LEGACY/user/hooks.ts
  src/api/API_LEGACY/user/index.ts
  src/api/notice/hooks.ts
  src/api/notice/index.ts
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/page/meetingList/Advertisement/AdCarousel.tsx
  src/components/page/meetingList/Advertisement/AdCarouselDotBtn.tsx
  src/components/page/meetingList/Advertisement/index.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
  src/components/page/meetingList/Card/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/MobileSize/index.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx
  yarn.lock
Labels: size/XXL

#860 Revert "Revert "프러덕션 배포"_ubuntu issue"
  .eslintrc.json
  .gitignore
  .yarn/install-state.gz
  ampli.json
  package.json
  pages/_app.tsx
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  pages/post/index.tsx
  src/__generated__/schema2.d.ts
  src/ampli/index.ts
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/API_LEGACY/user/hooks.ts
  src/api/API_LEGACY/user/index.ts
  src/api/notice/hooks.ts
  src/api/notice/index.ts
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/page/meetingList/Advertisement/AdCarousel.tsx
  src/components/page/meetingList/Advertisement/AdCarouselDotBtn.tsx
  src/components/page/meetingList/Advertisement/index.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/page/meetingList/Card/MobileSize/CardType.tsx
  src/components/page/meetingList/Card/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/MobileSize/index.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingList/Slider/NoticeSlider/NoticeSlider.tsx
  yarn.lock
Labels: size/XXL

#865 신고 드롭다운 기능 구현
  .yarn/install-state.gz
  package.json
  pages/post/index.tsx
  public/assets/svg/alert-triangle.svg
  public/assets/svg/clicked-dots-vertical.svg
  public/assets/svg/clicked-menu-icon.svg
  public/assets/svg/comment-write.svg
  public/assets/svg/dots-vertical.svg
  public/assets/svg/menu_icon.svg
  public/assets/svg/trash.svg
  src/__generated__/schema2.d.ts
  src/components/feed/FeedActionButton/FeedActionButton.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/feed/FeedReCommentContainer/FeedReCommentContainer.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
  src/components/page/meetingList/Advertisement/PostAlertModal.tsx
  src/components/page/meetingList/Advertisement/PostDeleteModal.tsx
  src/components/page/meetingList/Advertisement/index.tsx
  yarn.lock
Labels: size/XXL

#867 피드홈/피드상세/모임상세/댓글/대댓글 차단된 컨텐츠 UI + API 연결
  pages/post/index.tsx
  src/__generated__/schema2.d.ts
  src/components/blocker/CommentBlocker.tsx
  src/components/blocker/ContentBlocker.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.stories.ts
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/meetingList/Advertisement/index.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
Labels: size/XXL

#869 fix: writing 수정
  src/components/blocker/CommentBlocker.tsx
Labels: size/XS

#870 프러덕션 배포
  src/components/blocker/CommentBlocker.tsx
Labels: size/XS

#873 모임 개설 시 "개설자 소개" 선택 입력으로 변경 + POST meeting/v2 api 마이그레이션 + dev 서버 url 임시로 변경
  package.json
  pages/make/index.tsx
  src/__generated__/schema2.d.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/index.ts
  src/components/form/Presentation/index.tsx
  src/components/form/Textarea/index.tsx
  src/types/form.ts
Labels: size/S

#880 모임 개설 프로세스, 모임 신청 프로세스 개선 (삭제 항목 반영)
  .yarn/install-state.gz
  pages/_app.tsx
  pages/edit/index.tsx
  pages/make/index.tsx
  src/api/API_LEGACY/meeting/index.ts
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/loader/ButtonLoader.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/types/form.ts
  styles/globals.css
Labels: size/L

#881 MDS UI 롤백 및 모임 개설 이슈 해결
  .yarn/install-state.gz
  package.json
  pages/make/index.tsx
  src/components/form/Label/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/BaseSelect/BaseSelect.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetButton.tsx
  src/components/form/Select/Button/index.tsx
  src/components/form/Select/OptionItem/CheckboxOptionItem.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/form/TextInput/index.tsx
  src/components/form/Textarea/index.tsx
  src/types/form.ts
  yarn.lock
Labels: size/XL

#884 모임 개설 디자인 QA 반영
  src/components/form/Calendar/index.tsx
  src/components/form/FileInput/index.tsx
  src/components/form/Label/index.tsx
  src/components/form/Presentation/index.tsx
Labels: size/XS

#885 '모집 대상' 렌더링 되지 않던 버그 수정 + 사진 첨부 안해도 버튼 활성화되던 버그 수정
  .yarn/install-state.gz
  src/components/page/meetingDetail/Information/InformationPanel.tsx
  src/types/form.ts
Labels: size/XS

#887 캘린더 일요일부터 시작
  src/components/form/Calendar/index.tsx
Labels: size/XS

#889 모임 개설 QA : onSubmit 되지 않는 이슈
  .yarn/install-state.gz
  pages/make/index.tsx
Labels: size/XS

#891 mds color와 통일
  src/components/form/Calendar/index.tsx
  src/components/form/FileInput/index.tsx
  src/components/form/Select/BaseSelect/BaseSelect.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetButton.tsx
  src/components/form/Select/Button/index.tsx
  src/components/form/TextInput/index.tsx
  src/components/form/Textarea/index.tsx
Labels: size/S

#894 모집 대상, 모임장 소개 모바일 반응형 + 모임 수정 배경색 변경
  pages/edit/index.tsx
  src/components/form/Presentation/index.tsx
Labels: size/L

#895 프로덕션 배포
  pages/edit/index.tsx
  src/components/form/Presentation/index.tsx
Labels: size/L
