Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2024-10, with the labels that each got.

#897 모임 상세 조회 API 마이그레이션
  src/api/API_LEGACY/meeting/index.ts
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/form/Presentation/index.tsx
Labels: size/S

#899 모임 상세 조회 API 마이그레이션 배포
  src/api/API_LEGACY/meeting/index.ts
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/form/Presentation/index.tsx
Labels: size/S

#902 Revert "getmStartDate -> mStartDate"
  pages/edit/index.tsx
  src/__generated__/schema2.d.ts
Labels: size/XS

#909 모임상세조회 API 배포
  pages/edit/index.tsx
  src/__generated__/schema2.d.ts
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/API_LEGACY/user/index.ts
  src/api/post/index.ts
  src/components/page/meetingDetail/Carousel/index.tsx
  src/components/page/meetingDetail/Information/InformationPanel.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
Labels: size/M

#908 내 댓글 아닐 때 신고 버튼 뜨도록 수정 + 아이콘 원상복구
  .yarn/install-state.gz
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
Labels: size/M

#911 개설하기 버튼 클릭 시 입력 내용 확인 다이얼로그 추가
  .yarn/install-state.gz
  pages/_app.tsx
  src/components/form/Presentation/index.tsx
  styles/globals.ts
Labels: size/L

#913 활동 기간에 SOPT 공식 일정 안내 툴팁 추가
  .yarn/install-state.gz
  package.json
  public/assets/images/sopt_schedule_tooltip.png
  src/components/form/Presentation/index.tsx
  src/components/page/meetingManagement/ItemDescriptionBox.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
Labels: size/L

#914 모임 개설 대상 파트 Chip 으로 변경
  pages/post/index.tsx
  src/components/form/Presentation/JoinablePartsField/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/form/TextInput/index.tsx
  src/data/options.ts
Labels: size/L

#917 useMutationPostLike type에서 data 제거
  src/__generated__/schema2.d.ts
  src/api/post/hooks.ts
Labels: size/S

#924 Input 높이 및 모집 대상 chip 변경
  src/components/form/TextInput/index.tsx
  src/components/page/meetingDetail/Information/InformationPanel.tsx
  src/constants/option.ts
Labels: size/S

#926 모임안내 모집대상 chip QA 반영
  src/components/page/meetingDetail/Information/InformationPanel.tsx
Labels: size/XS

#922 모임 신청 취소하기 다이얼로그 MDS로 교체
  src/components/page/meetingDetail/MeetingController/index.tsx
Labels: size/S

#920 툴팁 디자인 QA 반영
  .yarn/install-state.gz
  package.json
  public/assets/svg/bubble_point.svg
  src/components/form/Presentation/index.tsx
  yarn.lock
Labels: size/L

#929 Chip 부분만 revert하고 변경사항들은 반영
  pages/post/index.tsx
  src/components/form/Presentation/JoinablePartsField/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/form/TextInput/index.tsx
  src/components/page/meetingDetail/Information/InformationPanel.tsx
  src/constants/option.ts
  src/data/options.ts
Labels: size/L

#932 Chip 파트 한 개 이슈 대응
  pages/edit/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/types/form.ts
Labels: size/XS

#937 모임 삭제 Dialog mds 교체
  package.json
  src/components/page/meetingDetail/MeetingController/Modal/Confirm/HostConfirmModal.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  yarn.lock
Labels: size/M

#938 Chip, dialog 배포
  package.json
  pages/edit/index.tsx
  src/components/form/Presentation/JoinablePartsField/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/page/meetingDetail/Information/InformationPanel.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Confirm/HostConfirmModal.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/constants/option.ts
  src/data/options.ts
  src/types/form.ts
  yarn.lock
Labels: size/L

#939 fix: 웹뷰 피드 작성 remainingHeight 변경
  src/components/feed/Modal/FeedFormPresentation.tsx
Labels: size/XS
