Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2024-05, with the labels that each got.

#723 mds 버전1 업그레이드
  package.json
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  yarn.lock
Labels: size/L

#724 yarn 버전 업그레이드 from v1 to v4 (mds 업데이트할 때, yarn update-mds 명령어 한 줄로 한 번에 간편하게!)
  .yarn/install-state.gz
  .yarn/releases/yarn-4.1.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: size/XXL

#728 모임 개설 Form UI 개선
  .yarn/install-state.gz
  pages/make/index.tsx
  public/assets/svg/checkBox/form_selected.svg
  public/assets/svg/checkBox/form_unselected.svg
  public/assets/svg/icon-interaction-plus.svg
  src/api/meeting/index.ts
  src/components/form/CheckBox/NeedMentor.tsx
  src/components/form/FileInput/index.tsx
  src/components/form/HelpMessage/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/BaseSelect/BaseSelect.tsx
  src/components/form/Select/OptionItem/CheckboxOptionItem.tsx
  src/components/form/Select/OptionItem/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/data/categories.ts
Labels: size/XL

#726 날짜 인풋폼 캘린더 형태로 변경
  .yarn/install-state.gz
  package.json
  public/assets/svg/calendar_big.svg
  src/components/form/Calendar/index.tsx
  src/components/form/Presentation/index.tsx
  styles/globals.css
  yarn.lock
Labels: size/L

#732 솝커톤 이슈 해결 : refetchQueries 로 데이터 페칭 후 모달 닫기
  .yarn/install-state.gz
  src/components/modal/ConfirmModal.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Confirm/GuestConfirmModal.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
Labels: size/M

#735 솝커톤 이슈 대응 - 서버 api 분리 (신청하기 api)
  .yarn/install-state.gz
  pages/detail/index.tsx
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/modal/ConfirmModal.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
Labels: size/M

#737 모임 신청하는 중 모달 닫히지 않게 하기
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/modal/ModalContainer.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Confirm/GuestConfirmModal.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
Labels: size/M

#739 모임 신청 중 에러 발생 시, alert에 에러 메시지 표시
  src/components/page/meetingDetail/MeetingController/index.tsx
Labels: size/XS

#742 feat: 모임 신청,취소하기 로더 UI추가 및 alert창 추가
  src/components/modal/ConfirmModal.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/ApplicationModalContent.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
Labels: size/XS

#744 모임 신청하는 중 onError 상황에서 refetchQueries 추가
  src/components/page/meetingDetail/MeetingController/index.tsx
Labels: size/S

#745 프로덕션 배포
  .yarn/install-state.gz
  .yarn/releases/yarn-4.1.1.cjs
  .yarnrc.yml
  package.json
  pages/detail/index.tsx
  pages/make/index.tsx
  public/assets/svg/calendar_big.svg
  public/assets/svg/checkBox/form_selected.svg
  public/assets/svg/checkBox/form_unselected.svg
  public/assets/svg/icon-interaction-plus.svg
  src/api/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/form/Calendar/index.tsx
  src/components/form/CheckBox/NeedMentor.tsx
  src/components/form/FileInput/index.tsx
  src/components/form/HelpMessage/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/Select/BaseSelect/BaseSelect.tsx
  src/components/form/Select/OptionItem/CheckboxOptionItem.tsx
  src/components/form/Select/OptionItem/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/DefaultModal.tsx
  src/components/modal/ModalContainer.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Confirm/GuestConfirmModal.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/ApplicationModalContent.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/data/categories.ts
  styles/globals.css
  yarn.lock
Labels: size/XXL

#747 신청자 관리 페이지에 홈 버튼 추가
  pages/mine/management/index.tsx
Labels: size/XS

#749 피드 작성 시간 표기 정상화
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
Labels: size/XS

#751 카카오톡 채팅 바로가기 버튼 기능 구현
  .env.sample
  pages/_app.tsx
  pages/_document.tsx
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  src/global.d.ts
  src/hooks/useSessionStorage.ts
  src/utils/ChannelService.ts
Labels: size/L

#756 깃허브 빌드 세팅 변경
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: size/XS

#752 Feat/#750 모임 피드 작성 시 플그 리다이렉션 액션 토스트 구현
  package.json
  pages/_app.tsx
  pages/post/index.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/feed/Modal/FeedFormPresentation.tsx
  yarn.lock
Labels: size/XXL

#758 fix: 카카오 플러스 친구 채팅 버튼 색상 변경
  .yarn/install-state.gz
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
Labels: size/XS

#759 프로덕션 배포
  .env.sample
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  .yarn/install-state.gz
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  pages/post/index.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
  src/global.d.ts
  src/hooks/useSessionStorage.ts
  src/utils/ChannelService.ts
  yarn.lock
Labels: size/XXL
