Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2024-04, with the labels that each got.

#689 fix: applicantCount 와 approvedUserCount 뒤바뀜 문제 픽스
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
Labels: size/XS

#692 프로덕션 배포
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
Labels: size/XS

#691 docs: 코드 리뷰어 멤버 변경
  .github/CODEOWNERS
  .github/workflows/AutomaticAssignReviewer.yml
Labels: size/XS

#694 swagger spring 문서 타입 추가 및 api 엔드포인트 변경
  package.json
  pages/post/index.tsx
  src/__generated__/schema.d.ts
Labels: size/XS

#695 프로덕션 배포
  .github/CODEOWNERS
  .github/workflows/AutomaticAssignReviewer.yml
  package.json
  pages/post/index.tsx
  src/__generated__/schema.d.ts
Labels: size/XS

#698 사소한 디자인 QA 및 활동 기간 api 수정
  public/assets/svg/GroupBrowsingCardSeparator.svg
  src/api/meeting/index.ts
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
Labels: size/M

#699 프로덕션 배포
  public/assets/svg/GroupBrowsingCardSeparator.svg
  src/api/meeting/index.ts
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
Labels: size/M

#701 throttle 사용해서 버튼 중복 클릭 방지
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/hooks/useThrottle.ts
Labels: size/M

#705 프로덕션 배포
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/hooks/useThrottle.ts
Labels: size/M

#706 codemods 를 활용한 nextjs 버전 업 (12 > 14)
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .storybook/main.ts
  README.md
  ampli.json
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  pages/post/index.tsx
  src/__generated__/schema.d.ts
  src/ampli/index.ts
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/groupBrowsing/mobileSizeCard.tsx
  src/components/header/Header.tsx
  src/components/modal/NoJoinedGroupModal.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  yarn.lock
Labels: size/XXL

#708 Revert "프로덕션 배포"
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .storybook/main.ts
  README.md
  ampli.json
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  pages/post/index.tsx
  src/__generated__/schema.d.ts
  src/ampli/index.ts
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/groupBrowsing/mobileSizeCard.tsx
  src/components/header/Header.tsx
  src/components/modal/NoJoinedGroupModal.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  yarn.lock
Labels: size/XXL

#709 프로덕션 배포 테스트
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .storybook/main.ts
  README.md
  ampli.json
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  pages/post/index.tsx
  src/__generated__/schema.d.ts
  src/ampli/index.ts
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/groupBrowsing/mobileSizeCard.tsx
  src/components/header/Header.tsx
  src/components/modal/NoJoinedGroupModal.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  yarn.lock
Labels: size/XXL

#710 Revert "프로덕션 배포 테스트 "
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .storybook/main.ts
  README.md
  ampli.json
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  pages/post/index.tsx
  src/__generated__/schema.d.ts
  src/ampli/index.ts
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/groupBrowsing/mobileSizeCard.tsx
  src/components/header/Header.tsx
  src/components/modal/NoJoinedGroupModal.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  yarn.lock
Labels: size/XXL

#713 프로덕션 배포 테스트
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .storybook/main.ts
  README.md
  ampli.json
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  pages/mine/management/index.tsx
  pages/post/index.tsx
  src/__generated__/schema.d.ts
  src/ampli/index.ts
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/groupBrowsing/mobileSizeCard.tsx
  src/components/header/Header.tsx
  src/components/modal/NoJoinedGroupModal.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingList/Card/ManagementButton.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  yarn.lock
Labels: size/XXL

#714 콘솔 추가 프로덕션 배포
  pages/_app.tsx
Labels: size/XS

#716 프로덕션 배포 에러 수정 : useEffect 의존성 배열 수정
  pages/_app.tsx
Labels: size/XS

#717 의존성 배열 수정 프로덕션 배포
  pages/_app.tsx
Labels: size/XS

#718 Revert "콘솔 추가 프로덕션 배포"
  pages/_app.tsx
Labels: size/XS
