Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2024-06, with the labels that each got.

#762 플레이그라운드 common 패키지 버전 업 + SDK init 과정을 페이지 단위에서 전역 단위로 변경
  .yarn/install-state.gz
  package.json
  pages/_app.tsx
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  src/global.d.ts
  yarn.lock
Labels: size/M

#763 프로덕션 배포
  .yarn/install-state.gz
  package.json
  pages/_app.tsx
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  src/global.d.ts
  yarn.lock
Labels: size/M

#765 upgrade: 플레이그라운드 공통 헤더 업그레이드 (끝말잇기 제외)
  .yarn/install-state.gz
  package.json
  yarn.lock
Labels: size/S

#766 프로덕션 배포
  .yarn/install-state.gz
  package.json
  yarn.lock
Labels: size/S

#768 feat: 내 모임에서 피드 작성 시 useThrottle 적용
  src/components/feed/Modal/FeedCreateModal.tsx
Labels: size/XS

#772 feat: 공유하러 가기 버튼 amplitude 이벤트 추가
  src/ampli/index.ts
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
Labels: size/L

#773 프로덕션 배포
  src/ampli/index.ts
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
Labels: size/L

#770 fix: 크로스 브라우징 이슈 해결을 위한 명확한 날짜 포맷 사용
  src/components/form/Calendar/index.tsx
Labels: size/XS

#774 모임 신청자 리스트 조회 API 마이그레이션
  pages/_app.tsx
  pages/detail/index.tsx
  pages/edit/index.tsx
  pages/index.tsx
  pages/list/index.tsx
  pages/make/index.tsx
  pages/mine/management/index.tsx
  pages/post/index.tsx
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/API_LEGACY/user/hooks.ts
  src/api/API_LEGACY/user/index.ts
  src/api/meeting/hook.ts
  src/api/meeting/index.ts
  src/api/post/index.ts
  src/api/user/index.ts
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/form/Presentation/index.tsx
  src/components/groupBrowsing/Carousel/Carousel.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/groupBrowsing/mobileSizeCard.tsx
  src/components/groupBrowsingSlider/groupBrowsingSlider.tsx
  src/components/header/Header.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/meetingDetail/Carousel/index.tsx
  src/components/page/meetingDetail/Feed/FeedItem/index.tsx
  src/components/page/meetingDetail/Feed/FeedPanel.tsx
  src/components/page/meetingDetail/Information/InformationPanel.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/ApplicationModalContent.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/page/meetingList/Card/MobileSize/ListType.tsx
  src/components/page/meetingList/Card/MobileSize/index.tsx
  src/components/page/meetingList/Card/Status.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Grid/List.tsx
  src/components/page/meetingManagement/Filter/index.tsx
  src/components/page/meetingManagement/ManagementListItem.tsx
  src/components/page/meetingManagement/MeetingInformation.tsx
  src/constants/option.ts
Labels: size/XL
