Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2024-11, with the labels that each got.

#946 @sopt-makers/playground-common 최신버전으로 업데이트
  package.json
  yarn.lock
Labels: size/S

#943 DELETE, POST, PUT post/v2 API 마이그레이션
  pages/post/index.tsx
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/page/meetingList/Advertisement/PostDeleteModal.tsx
Labels: size/S

#941 공동 모임장 UI 퍼블리싱
  packages/react-mentions/src/SuggestionsOverlay.js
  pages/_app.tsx
  pages/edit/index.tsx
  pages/make/index.tsx
  src/components/form/FormController/index.tsx
  src/components/form/HelpMessage/index.tsx
  src/components/form/Presentation/CoLeader/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/SearchMention/SearchMentionContext.tsx
  src/components/form/SearchMention/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/types/form.ts
Labels: size/XL

#944 Feat/#940
  pages/edit/index.tsx
  src/__generated__/schema2.d.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/user/index.ts
  src/components/feed/Mention/index.tsx
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/form/Presentation/CoLeader/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/SearchMention/index.tsx
  src/components/page/meetingDetail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/meetingDetail/MeetingController/ProfileAnchor.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
  src/components/page/meetingList/Card/DesktopSizeCard.tsx
  src/components/page/meetingList/Card/MobileSize/index.tsx
  src/components/page/meetingList/Card/index.tsx
  src/components/page/meetingList/Grid/List.tsx
Labels: size/L

#949 개설자 본인은 공동 모임장 검색이 되지 않도록 구현
  src/api/API_LEGACY/meeting/index.ts
  src/components/form/Presentation/CoLeader/index.tsx
Labels: size/S

#953 API 마이그레이션 마무리
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/auth/index.ts
Labels: size/S

#954 Revert "API 마이그레이션 마무리"
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/auth/index.ts
Labels: size/S

#961 me 제외 API 마이그레이션
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
Labels: size/S

#963 모임장 QA 반영
  src/components/form/CheckBox/NeedMentor.tsx
Labels: size/XS

#959 공동 모임장 QA 반영
  src/api/index.ts
  src/components/form/Presentation/CoLeader/index.tsx
  src/components/form/SearchMention/index.tsx
Labels: size/M

#966 프로덕션 배포
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/index.ts
  src/components/form/CheckBox/NeedMentor.tsx
  src/components/form/Presentation/CoLeader/index.tsx
  src/components/form/SearchMention/index.tsx
  src/components/page/meetingDetail/MeetingController/index.tsx
Labels: size/M
