Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2025-02, with the labels that each got.

#1001 필요없는 any 지우기 (any 는 타입스크립트가 아니에요!!)
  src/utils/gtm.ts
Labels: size/XS

#1006 번쩍 수정 API 연결
  pages/edit/flash/index.tsx
  pages/make/flash/index.tsx
  src/api/flash/index.ts
  src/components/form/Flash/index.tsx
  src/components/page/detail/MeetingController/index.tsx
Labels: size/M

#1004 [ Feature ] 번쩍 개설 시 최대 인원이 최소 인원보다 작을 때 에러 메시지 출력시키기
  pages/edit/flash/index.tsx
  src/api/flash/index.ts
  src/api/meeting/index.ts
  src/components/form/Flash/index.tsx
  src/types/form.ts
Labels: size/M

#997 전체 모임 필터 작업 및 UI 수정 작업 (필터 모달 삭제)
  package.json
  pages/list/index.tsx
  public/assets/svg/arrow_right_circle.svg
  src/components/page/list/Filter/DropDown/index.tsx
  src/components/page/list/Filter/Modal/Chip/ChipItem.tsx
  src/components/page/list/Filter/Modal/Chip/index.tsx
  src/components/page/list/Filter/Modal/Toggle/index.tsx
  src/components/page/list/Filter/Modal/index.tsx
  src/components/page/list/Filter/Result/index.tsx
  src/components/page/list/Filter/Search/index.tsx
  src/components/page/list/Filter/index.tsx
  src/constants/option.ts
  src/hooks/queryString/index.ts
  src/hooks/useDisplay.ts
Labels: size/L

#1008 번쩍 개설 시 이미지 width 를 고정값으로 변경 (디자인 측 요청사항)
  src/components/form/Flash/index.tsx
Labels: size/XS

#1010 '협의 후 결정' 체크 박스로 변경, QA 반영
  pages/edit/flash/index.tsx
  src/__generated__/schema2.d.ts
  src/components/form/Flash/index.tsx
  src/components/form/FormController/index.tsx
  src/components/form/SearchMention/index.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/types/form.ts
Labels: size/L

#1014 전체 모임 개편 (모든 필터 드롭다운으로 변경, 카카오톡 문의 버튼 구현 등등)
  pages/detail/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  public/assets/svg/logo_kakao.svg
  public/assets/svg/logo_kakao_32.svg
  src/components/form/TableOfContents/index.tsx
  src/components/kakaoFloatingButton/KakaoFloatingButton.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/list/Filter/DropDown/index.tsx
  src/components/page/list/Filter/Search/index.tsx
  src/components/page/list/Filter/index.tsx
  src/components/page/list/FloatingButton/index.tsx
  src/constants/option.ts
Labels: size/XL

#1018 전체 모임 개편 QA
  public/assets/svg/logo_kakao_28.svg
  src/components/kakaoFloatingButton/KakaoFloatingButton.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/list/Filter/DropDown/index.tsx
  src/components/page/list/FloatingButton/index.tsx
Labels: size/M

#1020 모바일 환영태그 안 뜨도록 수정
  src/components/page/detail/Information/InformationPanel.tsx
  src/components/page/detail/Information/constant.tsx
Labels: size/L

#1022 feat: 홈탭 플로팅 버튼 변경
  pages/detail/index.tsx
  pages/index.tsx
  pages/list/index.tsx
  pages/mine/index.tsx
  src/components/FloatingButton/index.tsx
  src/components/FloatingButton/kakaoFloatingButton/KakaoFloatingButton.tsx
  src/components/page/home/FloatingButton/index.tsx
Labels: size/S

#1025 협의 후 노출 표시
  pages/list/index.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/page/detail/Information/constant.tsx
  src/components/page/list/Card/DesktopSizeCard/constant.ts
Labels: size/XS

#1027 모임홈 반응형 적용 / QuickMenu 디자인 개선 / 전체모임 반응형 QA 반영
  .eslintrc.json
  pages/_app.tsx
  pages/detail/index.tsx
  pages/index.tsx
  pages/list/index.tsx
  public/assets/svg/button_bolt.svg
  public/assets/svg/button_event.svg
  public/assets/svg/button_seminar.svg
  public/assets/svg/button_study.svg
  src/components/GuideButton/index.tsx
  src/components/page/home/HomeCardList/CardList.tsx
  src/components/page/home/HomeCardList/index.tsx
  src/components/page/home/QuickMenu/index.tsx
Labels: size/L

#1029 QuickMenu 디자인 변경 및 번쩍 캐러셀 tablet까지 반영
  pages/index.tsx
  public/assets/svg/button_bolt.svg
  public/assets/svg/button_event.svg
  public/assets/svg/button_seminar.svg
  public/assets/svg/button_study.svg
  src/components/page/home/QuickMenu/index.tsx
Labels: size/M
