Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2025-09, with the labels that each got.

#1185 main << develop
  src/api/meeting/query.ts
  src/constant/activeGeneration.ts
  src/constant/option.ts
  src/domain/list/Filter/DropDown/index.tsx
Labels: size/S, release

#1186 모임 게시글 상세 페이지에서 좋아요 클릭 안 되는 이슈 해결
  src/api/post/PostQueryKey.ts
  src/api/post/mutation.ts
Labels: size/S

#1189 모임 개설 SOPT 공식 일정 확인하기 툴팁 37기 공식일정 기준으로 변경
  src/shared/form/Presentation/ActivityPeriodField/OfficialScheduleTooltop.tsx
Labels: size/S

#1190 main << develop
  .github/workflows/AutomaticAssignReviewer.yml
  src/api/post/PostQueryKey.ts
  src/api/post/mutation.ts
  src/domain/home/HomeCardList/DesktopCard.tsx
  src/domain/home/HomeCardList/MobileCard.tsx
  src/shared/form/Presentation/ActivityPeriodField/OfficialScheduleTooltop.tsx
Labels: size/M, release
