Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2025-01, with the labels that each got.

#972 [Feat/#971] 번쩍 개설 플로팅 버튼 추가, 필터링 카테고리 및 chip 추가, 멘토 구해요 라벨 삭제
  pages/list/index.tsx
  public/assets/svg/bolt_md.svg
  src/api/API_LEGACY/meeting/hooks.ts
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/list/Card/DesktopSizeCard.tsx
  src/components/page/list/Filter/Modal/Chip/index.tsx
  src/components/page/list/Filter/Result/index.tsx
  src/components/page/list/Filter/index.tsx
  src/components/page/list/Grid/List.tsx
  src/constants/option.ts
  src/hooks/queryString/custom.ts
  src/hooks/queryString/index.ts
Labels: size/M

#970 undefined 배열 요소 접근을 방지해주는, noUncheckedIndexedAccess 옵션 추가
  .github/workflows/deploy-development.yml
  pages/mine/management/index.tsx
  pages/post/index.tsx
  src/components/feed/FeedPostViewer/FeedPostViewer.tsx
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/form/Calendar/index.tsx
  src/components/form/Presentation/JoinablePartsField/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/SearchMention/index.tsx
  src/components/form/Select/BaseSelect/BaseSelect.tsx
  src/components/form/Select/BottomSheetSelect/BottomSheetSelect.tsx
  src/components/form/Select/OptionItem/index.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/groupBrowsing/mobileSizeCard.tsx
  src/components/page/detail/Information/InformationPanel.tsx
  src/components/page/home/HomeCardList/CardList.tsx
  src/components/page/list/Advertisement/AdCarousel.tsx
  src/components/page/list/Card/DesktopSizeCard.tsx
  src/components/page/list/Card/MobileSize/CardType.tsx
  src/components/page/list/Card/MobileSize/ListType.tsx
  src/components/page/list/Grid/List.tsx
  src/components/page/mine/management/MeetingInformation.tsx
  src/data/options.ts
  src/utils/dayjs.ts
  tsconfig.json
Labels: size/L

#974 홈탭 번쩍 캐러셀 및 모임 카드 MO
  pages/index.tsx
  public/assets/svg/location.svg
  src/components/groupBrowsing/Carousel/Carousel.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/page/home/HomeCardList/CardList.tsx
  src/components/page/home/HomeCardList/DesktopCard.tsx
  src/components/page/home/HomeCardList/MobileCard.tsx
  src/components/page/home/HomeCardList/index.tsx
  src/components/page/home/QuickMenu/index.tsx
Labels: size/XL

#978 번쩍 개설하기 UI 작업
  package.json
  pages/make/bungae/index.tsx
  public/assets/svg/bungae.svg
  src/components/form/Bungae/index.tsx
  src/data/options.ts
  src/types/form.ts
  yarn.lock
Labels: size/XXL

#980 번쩍 개설 API 연결 작업
  pages/make/bungae/index.tsx
  src/api/meeting/index.ts
  src/components/form/Bungae/index.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/data/options.ts
  src/types/form.ts
Labels: size/M

#976 모임카드 API 연결
  package.json
  pages/index.tsx
  src/__generated__/schema2.d.ts
  src/api/API_LEGACY/user/index.ts
  src/api/meeting/hook.ts
  src/api/meeting/index.ts
  src/api/post/index.ts
  src/components/page/home/HomeCardList/index.tsx
Labels: size/M

#984 번쩍 홈/전체/상세
  pages/detail/index.tsx
  pages/index.tsx
  pages/make/lightning/index.tsx
  pages/mine/management/index.tsx
  pages/post/index.tsx
  public/assets/svg/icon_bolt.svg
  public/assets/svg/icon_event.svg
  public/assets/svg/icon_seminar.svg
  public/assets/svg/icon_study.svg
  public/assets/svg/location.svg
  src/__generated__/schema2.d.ts
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/lightning/hook.ts
  src/api/lightning/index.ts
  src/api/meeting/index.ts
  src/components/Tag/RecruitmentStatusTag.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/FeedCommentViewer/FeedCommentViewer.tsx
  src/components/feed/Mention/index.tsx
  src/components/form/Bungae/index.tsx
  src/components/form/SearchMention/index.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/detail/Information/InformationPanel.tsx
  src/components/page/detail/Information/constant.tsx
  src/components/page/detail/MeetingController/LightningAbout.tsx
  src/components/page/detail/MeetingController/MeetingAbout.tsx
  src/components/page/detail/MeetingController/constant.ts
  src/components/page/detail/MeetingController/index.tsx
  src/components/page/home/HomeCardList/DesktopCard.tsx
  src/components/page/home/HomeCardList/MobileCard.tsx
  src/components/page/home/HomeCardList/index.tsx
  src/components/page/list/Advertisement/PostDeleteModal.tsx
  src/components/page/list/Card/DesktopSizeCard.tsx
  src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx
  src/components/page/list/Card/DesktopSizeCard/constant.ts
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/components/page/list/Card/MobileSize/CardType.tsx
  src/components/page/list/Card/MobileSize/ListType.tsx
  src/components/page/list/Card/MobileSize/index.tsx
  src/components/page/list/Card/index.tsx
  src/components/page/mine/management/ManagementListItem.tsx
  src/constants/option.ts
  src/data/options.ts
  src/hooks/useOverlay/OverlayProvider.tsx
  src/types/form.ts
Labels: size/XXL

#986 lightning -> flash 마이그레이션
  pages/detail/index.tsx
  pages/index.tsx
  pages/make/flash/index.tsx
  src/__generated__/schema2.d.ts
  src/api/flash/hook.ts
  src/api/flash/index.ts
  src/api/lightning/hook.ts
  src/api/meeting/index.ts
  src/components/form/Bungae/index.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/detail/Information/InformationPanel.tsx
  src/components/page/detail/Information/constant.tsx
  src/components/page/detail/MeetingController/FlashAbout.tsx
  src/components/page/detail/MeetingController/constant.ts
  src/components/page/detail/MeetingController/index.tsx
  src/components/page/list/Card/DesktopSizeCard/constant.ts
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/data/options.ts
  src/types/form.ts
Labels: size/L

#988 style: 마무리
  src/components/page/list/Card/DesktopSizeCard/constant.ts
Labels: size/XS

#991 feat: 모임 바꿈
  src/components/page/home/HomeCardList/index.tsx
Labels: size/S

#992 모임 픽스 배포
  src/components/page/home/HomeCardList/index.tsx
Labels: size/S

#994 QA: 협의 후 결정 여부에 따른 메시지 출력 여부 결정
  src/components/page/detail/Information/constant.tsx
Labels: size/XS

#995 프로덕션 배포
  src/components/page/detail/Information/constant.tsx
Labels: size/XS
