Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2025-06, with the labels that each got.

#1144 v1.0.1
  src/api/property/index.ts
  src/components/GuideButton/index.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipClose.tsx
  src/components/Tooltip/TooltipContent.tsx
  src/components/Tooltip/TooltipContext.ts
  src/components/Tooltip/TooltipHeader.tsx
  src/components/Tooltip/TooltipTrigger.tsx
  src/components/page/list/Card/DesktopSizeCard/constant.ts
Labels: size/L, release

#1139 Revert "Revert "v1.0.0""
  src/components/page/detail/Information/constant.tsx
  src/components/page/list/Filter/DropDown/index.tsx
Labels: size/XS

#1147 [Feat] 유저 관심 키워드(알림 설정) 기능 구현
  pages/index.tsx
  pages/list/index.tsx
  src/api/post/hooks.ts
  src/api/user/hooks.ts
  src/api/user/index.ts
  src/components/GuideButton/index.tsx
  src/components/KeywordsSettingButton/index.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipClose.tsx
  src/components/Tooltip/TooltipContent.tsx
  src/components/page/list/Alarm/BottomSheet/AlarmSettingBottomSheet.tsx
  src/components/page/list/Alarm/Modal/AlarmSettingModal.tsx
  src/data/options.ts
Labels: size/L

#1149 [feat] 모임 홈에는 가이드 버튼이 보이도록
  pages/index.tsx
  src/components/GuideButton/index.tsx
Labels: size/M

#1151 [Feat] 툴팁 모바일 반응형 디자인 수정 요청사항 적용
  src/components/CrewTab/index.tsx
  src/components/KeywordsSettingButton/index.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipContent.tsx
  src/components/page/list/AlarmSetting/SettingButton/SettingButton.css.ts
  src/components/page/list/AlarmSetting/SettingButton/SettingButton.tsx
  src/components/page/list/AlarmSetting/TooltipContent/TooltipContent.tsx
Labels: size/L

#1153 [Feat] MeetingInformation에 isValid 로직 추가
  src/components/page/list/Card/DesktopSizeCard/constant.ts
  src/components/page/list/Card/DesktopSizeCard/index.tsx
Labels: size/S

#1155 v1.1.0
  pages/index.tsx
  pages/list/index.tsx
  src/api/post/hooks.ts
  src/api/user/hooks.ts
  src/api/user/index.ts
  src/components/CrewTab/index.tsx
  src/components/GuideButton/index.tsx
  src/components/KeywordsSettingButton/index.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/TooltipClose.tsx
  src/components/Tooltip/TooltipContent.tsx
  src/components/page/list/Alarm/BottomSheet/AlarmSettingBottomSheet.tsx
  src/components/page/list/Alarm/Modal/AlarmSettingModal.tsx
  src/components/page/list/AlarmSetting/SettingButton/SettingButton.css.ts
  src/components/page/list/AlarmSetting/SettingButton/SettingButton.tsx
  src/components/page/list/AlarmSetting/TooltipContent/TooltipContent.tsx
  src/components/page/list/Card/DesktopSizeCard/constant.ts
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/data/options.ts
Labels: size/L

#1156 [Feat] 다중필터 amplitude 연결
  src/ampli/index.ts
  src/components/page/list/Filter/DropDown/index.tsx
Labels: size/M

#1158 v.1.1.1
  src/ampli/index.ts
  src/components/page/list/Filter/DropDown/index.tsx
Labels: size/M
