Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2025-03, with the labels that each got.

#1031 모임홈 반응형 적용
  pages/index.tsx
  src/components/groupBrowsing/Carousel/Carousel.tsx
  src/components/groupBrowsing/Carousel/NextArrow.tsx
  src/components/page/detail/Carousel/NextArrow.tsx
  src/components/page/detail/Carousel/index.tsx
  src/components/page/home/HomeCardList/CardList.tsx
  src/components/page/home/QuickMenu/index.tsx
Labels: size/M

#1034 feat: auth/v2 마이그레이션
  src/api/auth/index.ts
Labels: size/S

#1036 auth API header 제거
  src/api/auth/index.ts
  src/api/index.ts
Labels: size/XS

#1037 모임홈 반응형 QA 반영
  .github/CODEOWNERS
  .github/workflows/AutomaticAssignReviewer.yml
  src/components/groupBrowsing/Carousel/Carousel.tsx
  src/components/groupBrowsingSlider/groupBrowsingSlider.tsx
Labels: size/M

#1040 피드 개설시, mention bug QA 반영
  src/components/feed/Modal/FeedCreateModal.tsx
Labels: size/S

#1042 더보기 버튼(⋮) 작동 오류, 피드 삭제 기능 버그 수정 QA
  pages/post/index.tsx
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/feed/FeedActionsContainer/index.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/page/detail/Feed/FeedPanel.tsx
  src/components/page/list/Advertisement/index.tsx
Labels: size/L

#1052 이미지 리사이저 시범 적용 (병합 오류 해결)
  src/components/page/home/HomeCardList/DesktopCard.tsx
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/components/page/list/Card/MobileSize/CardType.tsx
  src/components/page/list/Card/MobileSize/ListType.tsx
  src/utils/image.ts
Labels: size/S

#1054 공식일정 툴팁 및 다이얼로그 텍스트 변경
  src/components/form/Presentation/index.tsx
Labels: size/L

#1049 필요 없는 patch 파일 삭제, useEffect 개선점 발굴
  .yarn/patches/react-mentions-npm-4.4.10-a16f7ff8f6.patch
  pages/edit/flash/index.tsx
  pages/edit/index.tsx
  src/components/feed/Mention/index.tsx
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/form/FormController/index.tsx
  src/components/page/list/Pagination.tsx
  src/hooks/useOverlay/OverlayController.tsx
Labels: size/S

#1057 이미지 리사이징 프로덕션 배포를 위한 PR
  src/components/page/home/HomeCardList/DesktopCard.tsx
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/components/page/list/Card/MobileSize/CardType.tsx
  src/components/page/list/Card/MobileSize/ListType.tsx
  src/utils/image.ts
Labels: size/S

#1058 Revert "이미지 리사이징 프로덕션 배포를 위한 PR"
  src/components/page/home/HomeCardList/DesktopCard.tsx
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/components/page/list/Card/MobileSize/CardType.tsx
  src/components/page/list/Card/MobileSize/ListType.tsx
  src/utils/image.ts
Labels: size/S

#1055 모집 현황 신청자 넘버링
  src/__generated__/schema2.d.ts
  src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx
Labels: size/M

#1062 환영 Tag, 모집 상태 Tag 디자인 개선
  src/components/Tag/RecruitmentStatusTag.tsx
  src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx
Labels: size/M

#1063 Tag 폰트 크기 수정
  src/components/Tag/RecruitmentStatusTag.tsx
Labels: size/S

#1060 QA 반영 배포
  .yarn/patches/react-mentions-npm-4.4.10-a16f7ff8f6.patch
  pages/detail/flash/index.tsx
  pages/detail/index.tsx
  pages/edit/flash/index.tsx
  pages/edit/index.tsx
  pages/list/index.tsx
  pages/post/index.tsx
  src/__generated__/schema2.d.ts
  src/api/post/hooks.ts
  src/api/post/index.ts
  src/components/Tag/RecruitmentStatusTag.tsx
  src/components/feed/FeedActionsContainer/index.tsx
  src/components/feed/Mention/index.tsx
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/form/FormController/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/page/detail/Feed/FeedPanel.tsx
  src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx
  src/components/page/detail/index.tsx
  src/components/page/home/HomeCardList/DesktopCard.tsx
  src/components/page/list/Advertisement/index.tsx
  src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx
  src/components/page/list/Card/DesktopSizeCard/DesktopSizeFlashCard.tsx
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/components/page/list/Card/MobileSize/CardType.tsx
  src/components/page/list/Card/MobileSize/ListType.tsx
  src/components/page/list/Card/index.tsx
  src/components/page/list/Pagination.tsx
  src/hooks/useOverlay/OverlayController.tsx
  src/utils/image.ts
Labels: size/XXL
