Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2025-10, with the labels that each got.

#1194 모임 홈 스터디 카드 제목 타이포그래피 수정
  src/domain/home/HomeCardList/DesktopCard.tsx
Labels: size/XS

#1197 신청자 리스트 필터링/정렬/페이지네이션 오류 수정
  package.json
  pages/_app.tsx
  pages/mine/management/index.tsx
  src/api/meeting/MeetingQueryKey.ts
  src/api/meeting/mutation.ts
  src/api/meeting/query.ts
  src/domain/mine/management/ManagementForHost/ManagementListItemForHost.tsx
  yarn.lock
Labels: size/M

#1198 main << develop
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/mine/management/index.tsx
  src/api/meeting/MeetingQueryKey.ts
  src/api/meeting/mutation.ts
  src/api/meeting/query.ts
  src/domain/home/HomeCardList/DesktopCard.tsx
  src/domain/mine/management/ManagementForHost/ManagementListItemForHost.tsx
  src/shared/groupBrowsing/Carousel/Carousel.tsx
  src/shared/groupBrowsingSlider/groupBrowsingSlider.tsx
  yarn.lock
Labels: size/L, release

#1199 신청자 리스트 정렬 오류 수정
  src/data/options.ts
Labels: size/XS

#1202 Home 레이아웃 리팩토링
  pages/_app.tsx
  pages/index.tsx
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/api/index.ts
  src/constant/environment.ts
  src/constant/url.ts
  src/domain/home/HomeCardList/CardList.tsx
  src/domain/home/HomeCardList/DesktopCard.tsx
  src/domain/home/HomeCardList/index.tsx
  stitches.config.ts
Labels: size/L

#1204 main << develop
  src/api/meeting/mutation.ts
  src/data/options.ts
Labels: size/XS
