Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2025-04, with the labels that each got.

#1070 카테고리명 안 보이는 이슈 핫픽스 배포
  src/components/groupBrowsing/mobileSizeCard.tsx
  src/components/page/home/HomeCardList/DesktopCard.tsx
  src/components/page/home/HomeCardList/MobileCard.tsx
  src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx
  src/components/page/list/Card/DesktopSizeCard/index.tsx
Labels: size/S, release

#1065 [Feat/#1064] 공동 모임장 안드/아요 검색 안 됨 이슈
  src/components/form/Presentation/CoLeader/index.tsx
  src/components/form/SearchMention/index.tsx
Labels: size/XS

#1072 fix: width 잘못 설정되어 이미지 흐리게 보이는 이슈 수정
  src/components/page/home/HomeCardList/DesktopCard.tsx
Labels: size/XS

#1047 Feat/#1011 : 캘린더 ui 개선 ( 기간 선택, 아이콘 반응형)
  pages/edit/flash/index.tsx
  pages/edit/index.tsx
  public/assets/svg/calendar.svg
  public/assets/svg/calendar_big.svg
  src/api/API_LEGACY/meeting/index.ts
  src/api/flash/index.ts
  src/api/meeting/index.ts
  src/components/form/Calendar/index.tsx
  src/components/form/Flash/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/groupBrowsing/GroupBrowsingCard/GroupBrowsingCard.tsx
  src/components/page/detail/Information/constant.tsx
  src/types/form.ts
  src/utils/date.ts
  src/utils/dayjs.ts
  styles/globals.css
Labels: size/XL

#1077 모임홈 Editable Content 변경
  src/components/page/home/HomeCardList/index.tsx
Labels: size/S

#1080 Refresh token 로직 추가
  pages/_app.tsx
Labels: size/S

#1081 refresh token 로직 추가 배포
  pages/_app.tsx
Labels: size/S

#1084 dev 토큰 갱신 시간 2분 설정
  pages/_app.tsx
Labels: size/XS

#1086 사용자 해상도 ampli 추가
  pages/_app.tsx
  src/ampli/index.ts
Labels: size/M

#1087 dev 토큰 갱신 시간 / 캘린더 문제 해결 핫픽스 / 해상도 ampli 추가 배포
  .gitignore
  pages/_app.tsx
  pages/edit/flash/index.tsx
  pages/edit/index.tsx
  pages/make/index.tsx
  src/ampli/index.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/flash/index.ts
  src/api/meeting/index.ts
  src/components/form/Calendar/index.tsx
  src/components/form/Flash/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/types/form.ts
  src/utils/date.ts
  src/utils/dayjs.ts
  styles/globals.css
Labels: size/XL, release

#1067 신청자 관리 / 참여자 리스트 개선
  .vscode/settings.json
  pages/mine/management/index.tsx
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/page/mine/management/ItemDescriptionBox.tsx
  src/components/page/mine/management/ManagementListItem.tsx
  src/components/page/mine/management/ManagementListItemForHost.tsx
  src/utils/addHypenToPhoneNumber.ts
Labels: size/XL

#1088 신청자 리스트 순서 방식 변경
  pages/mine/management/index.tsx
  src/components/form/SearchMention/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/page/list/Grid/List.tsx
Labels: size/S

#1090 create-feed 모달 라우팅 처리
  src/components/FloatingButton/index.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/home/FloatingButton/index.tsx
Labels: size/L

#1093 신청자 리스트 QA 반영
  pages/mine/management/index.tsx
  src/components/page/mine/management/ManagementListItem.tsx
Labels: size/M

#1095 @sopt-makers/playground-common 버전 업데이트
  package.json
  yarn.lock
Labels: size/S

#1092 신청자 관리 / 참여자 리스트 개선 및 피드 모달 라우팅 처리 배포
  .vscode/settings.json
  package.json
  pages/mine/management/index.tsx
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/meeting/index.ts
  src/components/FloatingButton/index.tsx
  src/components/form/SearchMention/index.tsx
  src/components/form/TableOfContents/index.tsx
  src/components/modal/FloatingButtonModal.tsx
  src/components/page/home/FloatingButton/index.tsx
  src/components/page/list/Grid/List.tsx
  src/components/page/mine/management/ItemDescriptionBox.tsx
  src/components/page/mine/management/ManagementListItem.tsx
  src/components/page/mine/management/ManagementListItemForHost.tsx
  src/utils/addHypenToPhoneNumber.ts
  yarn.lock
Labels: size/XXL, release

#1097 신청 현황 모달 QA 반영
  src/components/modal/DefaultModal.tsx
  src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx
  src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/detail/MeetingController/index.tsx
Labels: size/L

#1098 신청 현황 모달 QA 반영 배포
  src/components/modal/DefaultModal.tsx
  src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/RecruitmentStatusList.tsx
  src/components/page/detail/MeetingController/Modal/Content/RecruitmentStatusModalContent/index.tsx
  src/components/page/detail/MeetingController/index.tsx
Labels: size/L
