Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2025-05, with the labels that each got.

#1100 [Feat/#1045] 다중 필터 기능 적용
  package.json
  src/api/API_LEGACY/meeting/index.ts
  src/components/page/list/Filter/DropDown/index.tsx
  src/components/page/list/Filter/Reset/index.tsx
  src/components/page/list/Filter/index.tsx
  yarn.lock
Labels: size/L

#1103 Management Host Guest 컴포넌트 분리
  pages/mine/management/index.tsx
  src/components/page/mine/management/ManagementForGuest/ManagementHeaderForGuest.tsx
  src/components/page/mine/management/ManagementForGuest/ManagementListItemForGuest.tsx
  src/components/page/mine/management/ManagementForGuest/index.tsx
  src/components/page/mine/management/ManagementForHost/ItemDescriptionBox.tsx
  src/components/page/mine/management/ManagementForHost/ManagementHeaderForHost.tsx
  src/components/page/mine/management/ManagementForHost/ManagementListItemForHost.tsx
  src/components/page/mine/management/ManagementForHost/index.tsx
Labels: size/XL

#1108 키워드 추가 마무리
  src/__generated__/schema2.d.ts
  src/components/page/list/Card/DesktopSizeCard/DesktopSizeFlashCard.tsx
  src/components/page/list/Card/DesktopSizeCard/constant.ts
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/data/options.ts
Labels: size/S

#1112 Presentation 컴포넌트 내 Field 컴포넌트 분리
  src/components/form/Presentation/ActivityPeriodField/OfficialScheduleTooltop.tsx
  src/components/form/Presentation/ActivityPeriodField/index.tsx
  src/components/form/Presentation/ApplicationPeriodField/index.tsx
  src/components/form/Presentation/CategoryField/index.tsx
  src/components/form/Presentation/CoLeaderField/CoLeader.tsx
  src/components/form/Presentation/CoLeaderField/index.tsx
  src/components/form/Presentation/DescriptionField/index.tsx
  src/components/form/Presentation/FlashPresentation/index.tsx
  src/components/form/Presentation/ImageField/ImagePreview.tsx
  src/components/form/Presentation/ImageField/index.tsx
  src/components/form/Presentation/ImageField/useImageHandler.ts
  src/components/form/Presentation/LeaderDescriptionField/NeedMentor.tsx
  src/components/form/Presentation/LeaderDescriptionField/index.tsx
  src/components/form/Presentation/NoticeField/index.tsx
  src/components/form/Presentation/ProcessIntroductionField/index.tsx
  src/components/form/Presentation/SubmitPresentationButton/index.tsx
  src/components/form/Presentation/TargetField/MemberCountField.tsx
  src/components/form/Presentation/TargetField/index.tsx
  src/components/form/Presentation/TitleField/index.tsx
  src/components/form/Presentation/index.tsx
Labels: size/XXL

#1113 모임 키워드화 QA 반영
  pages/edit/flash/index.tsx
  pages/edit/index.tsx
  pages/make/flash/index.tsx
  pages/make/index.tsx
  src/components/form/Presentation/KeywordField/index.tsx
  src/types/form.ts
Labels: size/L

#1106 전체 모임 탭에 키워드 필터 추가
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/components/page/list/Filter/DropDown/index.tsx
  src/components/page/list/Filter/Reset/index.tsx
  src/components/page/list/Filter/index.tsx
  src/constants/option.ts
  src/hooks/queryString/custom.ts
Labels: size/L

#1114 sp2. 모임 키워드화 배포
  package.json
  pages/detail/index.tsx
  pages/edit/flash/index.tsx
  pages/edit/index.tsx
  pages/make/flash/index.tsx
  pages/make/index.tsx
  pages/mine/management/index.tsx
  src/__generated__/schema2.d.ts
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/API_LEGACY/user/index.ts
  src/api/flash/index.ts
  src/api/meeting/index.ts
  src/components/form/Presentation/ActivityPeriodField/OfficialScheduleTooltop.tsx
  src/components/form/Presentation/ActivityPeriodField/index.tsx
  src/components/form/Presentation/ApplicationPeriodField/index.tsx
  src/components/form/Presentation/CategoryField/index.tsx
  src/components/form/Presentation/CoLeaderField/CoLeader.tsx
  src/components/form/Presentation/CoLeaderField/index.tsx
  src/components/form/Presentation/DescriptionField/index.tsx
  src/components/form/Presentation/FlashPresentation/index.tsx
  src/components/form/Presentation/ImageField/ImagePreview.tsx
  src/components/form/Presentation/ImageField/index.tsx
  src/components/form/Presentation/ImageField/useImageHandler.ts
  src/components/form/Presentation/KeywordField/index.tsx
  src/components/form/Presentation/LeaderDescriptionField/NeedMentor.tsx
  src/components/form/Presentation/LeaderDescriptionField/index.tsx
  src/components/form/Presentation/NoticeField/index.tsx
  src/components/form/Presentation/ProcessIntroductionField/index.tsx
  src/components/form/Presentation/SubmitPresentationButton/index.tsx
  src/components/form/Presentation/TargetField/MemberCountField.tsx
  src/components/form/Presentation/TargetField/index.tsx
  src/components/form/Presentation/TitleField/index.tsx
  src/components/form/Presentation/WelcomeMessageField/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/page/detail/Information/constant.tsx
  src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx
  src/components/page/list/Card/DesktopSizeCard/DesktopSizeFlashCard.tsx
  src/components/page/list/Card/DesktopSizeCard/constant.ts
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/components/page/list/Card/MobileSize/ListType.tsx
  src/components/page/list/Card/MobileSize/index.tsx
  src/components/page/list/Card/index.tsx
  src/components/page/list/Filter/DropDown/index.tsx
  src/components/page/list/Filter/Reset/index.tsx
  src/components/page/list/Filter/index.tsx
  src/components/page/list/Grid/List.tsx
  src/components/page/mine/management/ManagementForGuest/ManagementHeaderForGuest.tsx
  src/components/page/mine/management/ManagementForGuest/ManagementListItemForGuest.tsx
  src/components/page/mine/management/ManagementForGuest/index.tsx
  src/components/page/mine/management/ManagementForHost/ItemDescriptionBox.tsx
  src/components/page/mine/management/ManagementForHost/ManagementHeaderForHost.tsx
  src/components/page/mine/management/ManagementForHost/ManagementListItemForHost.tsx
  src/components/page/mine/management/ManagementForHost/index.tsx
  src/constants/option.ts
  src/data/options.ts
  src/hooks/queryString/custom.ts
  src/types/form.ts
  yarn.lock
Labels: size/XXL, release

#1115 Revert "sp2. 모임 키워드화 배포"
  package.json
  pages/detail/index.tsx
  pages/edit/flash/index.tsx
  pages/edit/index.tsx
  pages/make/flash/index.tsx
  pages/make/index.tsx
  pages/mine/management/index.tsx
  src/__generated__/schema2.d.ts
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/API_LEGACY/user/index.ts
  src/api/flash/index.ts
  src/api/meeting/index.ts
  src/components/form/CheckBox/NeedMentor.tsx
  src/components/form/Flash/index.tsx
  src/components/form/Presentation/ActivityPeriodField/OfficialScheduleTooltop.tsx
  src/components/form/Presentation/ActivityPeriodField/index.tsx
  src/components/form/Presentation/ApplicationPeriodField/index.tsx
  src/components/form/Presentation/CategoryField/index.tsx
  src/components/form/Presentation/CoLeader/index.tsx
  src/components/form/Presentation/CoLeaderField/index.tsx
  src/components/form/Presentation/DescriptionField/index.tsx
  src/components/form/Presentation/ImageField/index.tsx
  src/components/form/Presentation/ImageField/useImageHandler.ts
  src/components/form/Presentation/ImagePreview/index.tsx
  src/components/form/Presentation/KeywordField/index.tsx
  src/components/form/Presentation/LeaderDescriptionField/index.tsx
  src/components/form/Presentation/NoticeField/index.tsx
  src/components/form/Presentation/ProcessIntroductionField/index.tsx
  src/components/form/Presentation/SubmitPresentationButton/index.tsx
  src/components/form/Presentation/TargetField/MemberCountField.tsx
  src/components/form/Presentation/TargetField/index.tsx
  src/components/form/Presentation/TitleField/index.tsx
  src/components/form/Presentation/WelcomeMessageField/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/page/detail/Information/constant.tsx
  src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx
  src/components/page/list/Card/DesktopSizeCard/DesktopSizeFlashCard.tsx
  src/components/page/list/Card/DesktopSizeCard/constant.ts
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/components/page/list/Card/MobileSize/ListType.tsx
  src/components/page/list/Card/MobileSize/index.tsx
  src/components/page/list/Card/index.tsx
  src/components/page/list/Filter/DropDown/index.tsx
  src/components/page/list/Filter/Reset/index.tsx
  src/components/page/list/Filter/index.tsx
  src/components/page/list/Grid/List.tsx
  src/components/page/mine/management/ItemDescriptionBox.tsx
  src/components/page/mine/management/ManagementForGuest/ManagementHeaderForGuest.tsx
  src/components/page/mine/management/ManagementForGuest/index.tsx
  src/components/page/mine/management/ManagementForHost/ManagementHeaderForHost.tsx
  src/components/page/mine/management/ManagementForHost/index.tsx
  src/components/page/mine/management/ManagementListItem.tsx
  src/components/page/mine/management/ManagementListItemForHost.tsx
  src/constants/option.ts
  src/data/options.ts
  src/hooks/queryString/custom.ts
  src/types/form.ts
  yarn.lock
Labels: size/XXL

#1118 Sp2. 키워드 추가 재배포
  package.json
  pages/detail/index.tsx
  pages/edit/flash/index.tsx
  pages/edit/index.tsx
  pages/make/flash/index.tsx
  pages/make/index.tsx
  pages/mine/management/index.tsx
  src/__generated__/schema2.d.ts
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
  src/api/API_LEGACY/user/index.ts
  src/api/flash/index.ts
  src/api/meeting/index.ts
  src/components/form/Presentation/ActivityPeriodField/OfficialScheduleTooltop.tsx
  src/components/form/Presentation/ActivityPeriodField/index.tsx
  src/components/form/Presentation/ApplicationPeriodField/index.tsx
  src/components/form/Presentation/CategoryField/index.tsx
  src/components/form/Presentation/CoLeaderField/CoLeader.tsx
  src/components/form/Presentation/CoLeaderField/index.tsx
  src/components/form/Presentation/DescriptionField/index.tsx
  src/components/form/Presentation/FlashPresentation/index.tsx
  src/components/form/Presentation/ImageField/ImagePreview.tsx
  src/components/form/Presentation/ImageField/index.tsx
  src/components/form/Presentation/ImageField/useImageHandler.ts
  src/components/form/Presentation/KeywordField/index.tsx
  src/components/form/Presentation/LeaderDescriptionField/NeedMentor.tsx
  src/components/form/Presentation/LeaderDescriptionField/index.tsx
  src/components/form/Presentation/NoticeField/index.tsx
  src/components/form/Presentation/ProcessIntroductionField/index.tsx
  src/components/form/Presentation/SubmitPresentationButton/index.tsx
  src/components/form/Presentation/TargetField/MemberCountField.tsx
  src/components/form/Presentation/TargetField/index.tsx
  src/components/form/Presentation/TitleField/index.tsx
  src/components/form/Presentation/WelcomeMessageField/index.tsx
  src/components/form/Presentation/index.tsx
  src/components/page/detail/Information/constant.tsx
  src/components/page/list/Card/DesktopSizeCard/CategoryChip.tsx
  src/components/page/list/Card/DesktopSizeCard/DesktopSizeFlashCard.tsx
  src/components/page/list/Card/DesktopSizeCard/constant.ts
  src/components/page/list/Card/DesktopSizeCard/index.tsx
  src/components/page/list/Card/MobileSize/ListType.tsx
  src/components/page/list/Card/MobileSize/index.tsx
  src/components/page/list/Card/index.tsx
  src/components/page/list/Filter/DropDown/index.tsx
  src/components/page/list/Filter/Reset/index.tsx
  src/components/page/list/Filter/index.tsx
  src/components/page/list/Grid/List.tsx
  src/components/page/mine/management/ManagementForGuest/ManagementHeaderForGuest.tsx
  src/components/page/mine/management/ManagementForGuest/ManagementListItemForGuest.tsx
  src/components/page/mine/management/ManagementForGuest/index.tsx
  src/components/page/mine/management/ManagementForHost/ItemDescriptionBox.tsx
  src/components/page/mine/management/ManagementForHost/ManagementHeaderForHost.tsx
  src/components/page/mine/management/ManagementForHost/ManagementListItemForHost.tsx
  src/components/page/mine/management/ManagementForHost/index.tsx
  src/constants/option.ts
  src/data/options.ts
  src/hooks/queryString/custom.ts
  src/types/form.ts
  yarn.lock
Labels: size/XXL

#1122 페이지네이션 이슈 핫픽스
  src/api/API_LEGACY/meeting/index.ts
Labels: size/XS

#1120 isOnlyActiveGeneration 필터 오류 HOTFIX
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
Labels: size/S

#1123 모임 필터링 관련 핫픽스 배포
  src/api/API_LEGACY/meeting/hooks.ts
  src/api/API_LEGACY/meeting/index.ts
Labels: size/S, release

#1125 모임 상세 페이지에서 환영 태그 disabled 처리
  src/components/page/detail/Information/constant.tsx
Labels: size/XS

#1127 전체모임 다중필터 debounce 시간 조정
  src/components/page/list/Filter/DropDown/index.tsx
Labels: size/XS

#1136 Editable Contents API 연결
  pages/index.tsx
  src/api/property/hooks.ts
  src/api/property/index.ts
  src/components/page/home/HomeCardList/CardList.tsx
  src/components/page/home/HomeCardList/index.tsx
Labels: size/M

#1137 v1.0.0
  pages/index.tsx
  src/api/property/hooks.ts
  src/api/property/index.ts
  src/components/page/detail/Information/constant.tsx
  src/components/page/home/HomeCardList/CardList.tsx
  src/components/page/home/HomeCardList/index.tsx
  src/components/page/list/Filter/DropDown/index.tsx
Labels: size/M, release

#1138 Revert "v1.0.0"
  pages/index.tsx
  src/api/property/hooks.ts
  src/api/property/index.ts
  src/components/page/detail/Information/constant.tsx
  src/components/page/home/HomeCardList/CardList.tsx
  src/components/page/home/HomeCardList/index.tsx
  src/components/page/list/Filter/DropDown/index.tsx
Labels: size/M
