Repository sopt-makers/sopt-crew-frontend, pull requests merged in 2025-08, with the labels that each got.

#1162 [Hotfix] auth api Token 주입 방식 변경
  src/api/auth/index.ts
Labels: size/S

#1164 [Fix] 인증중앙화로 인한 크루 토큰 삭제 및 엑세스 토큰 로직 수정
  .env.sample
  pages/_app.tsx
  src/api/auth/index.ts
  src/api/index.ts
  src/components/util/auth.ts
  src/stores/tokenStore.ts
Labels: size/L

#1170 React Query v5로 버전업
  package.json
  pages/edit/flash/index.tsx
  pages/edit/index.tsx
  pages/make/flash/index.tsx
  pages/make/index.tsx
  pages/post/index.tsx
  src/api/comment/mutation.ts
  src/api/meeting/hook.ts
  src/api/post/hooks.ts
  src/api/post/mutation.ts
  src/api/user/hooks.ts
  src/api/user/mutation.ts
  src/components/FloatingButton/index.tsx
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedCreateWithSelectMeetingModal.tsx
  src/components/feed/Modal/FeedEditModal.tsx
  src/components/page/detail/Feed/FeedPanel.tsx
  yarn.lock
Labels: size/L

#1173 사용하지 않는 변수 및 컴포넌트 삭제
  pages/mine/index.tsx
  pages/post/index.tsx
  src/components/Tooltip/TooltipHeader.tsx
  src/components/feed/FeedCommentContainer/FeedCommentContainer.tsx
  src/components/feed/Modal/FeedCreateModal.tsx
  src/components/feed/Modal/FeedFormPresentation.tsx
  src/components/form/Calendar/index.tsx
  src/components/form/FormSwitch/FormSwitch.tsx
  src/components/form/Presentation/CoLeaderField/CoLeader.tsx
  src/components/form/Presentation/FlashPresentation/index.tsx
  src/components/form/Presentation/TargetField/MemberCountField.tsx
  src/components/form/Presentation/TargetField/index.tsx
  src/components/form/SearchMention/index.tsx
  src/components/form/Select/OptionItem/CheckboxOptionItem.tsx
  src/components/form/Select/OptionItem/MobileOptionItem.tsx
  src/components/page/detail/Feed/FeedPanel.tsx
  src/components/page/detail/Information/InformationPanel.tsx
  src/components/page/list/Filter/DropDown/index.tsx
  src/components/page/list/Filter/Modal/BottomSheet/InitializationButton.tsx
  src/components/page/list/Filter/Modal/BottomSheet/index.tsx
  src/components/page/list/Filter/Modal/Chip/ChipItem.tsx
  src/components/page/list/Filter/Modal/OpenButton.tsx
  src/components/page/list/Filter/Modal/index.tsx
  src/components/page/list/Filter/Result/ResultItem.tsx
  src/components/page/list/Filter/Result/index.tsx
  src/components/page/list/Grid/List.tsx
  src/components/page/list/Slider/NoticeSlider/DotWrapper.tsx
  src/components/page/list/Slider/NoticeSlider/NoticeSlider.tsx
  src/components/page/mine/management/ManagementForGuest/index.tsx
  src/hooks/useOverlay/OverlayController.tsx
  src/hooks/useScrollRestoration.ts
  src/hooks/useToast/Toast.tsx
Labels: size/XL
